### ISSUE TITLE
Failure at getting list items with a column entitled "Comments"

### ISSUE THREAD

**Issue by JakubTracz** [pnp/pnpcore#979] opened 2022-09-29 09:16 UTC
## Category

- [x] Bug

## Describe the bug

When fetching data from a list, it fails on JSON mapping if a table contains a column named "Comments".

![image](https://user-images.githubusercontent.com/53979165/192992051-2be1edee-1888-4585-8981-d990d256cd3c.png)

![image](https://user-images.githubusercontent.com/53979165/192991670-fb83fc7b-a455-48d0-ab6d-7de90da97e2a.png)

Does not happen with columns with a different name.

## Steps to reproduce

1.Create a new SharePoint list.
2.Add a new columns named Comments as single, non-mandatory line of text.
3.Add new item with some comment
4.Try to fetch the items via Items.ToListAsync()

## Expected behavior

I expect the items to be fetched. Instead a parsing error occurs.

## Environment details (*development & target environment*)

- **SDK version**: 6.0
- **OS**: Windows 10
- **SDK used in**: WPF app
- **Framework**: .NET 6
- **Browser(s)**: N/A
- **Tooling**: Rider
- **Additional details**: N/A

### Additional context
N/A

**Comment by jansenbe** [comment] 2022-09-29 15:00
@JakubTracz : you see this only with the comments column ore also with other columns?

**Comment by jansenbe** [comment] 2022-09-29 18:29
Interesting but weird issue you've found there @JakubTracz ... I can repro, now trying to understand the 'why' and fix it.

**Comment by jansenbe** [comment] 2022-09-30 12:34
@JakubTracz : found the root cause (Comments is also a collection on IListItem) and now testing a fix.

**Comment by jansenbe** [comment] 2022-09-30 17:30
@JakubTracz : fix has been committed. Thanks for using PnP Core SDK and reporting this issue. You can test the fix via the next nightly release (version 1.7.86 or higher).

**Closed by jansenbe** 2022-09-30 17:30 UTC
Labels: bug, area: model 📐
