### ISSUE TITLE
IListItem.EnsurePropertiesAsync(l => l.Values) fails to retrieve values

### ISSUE THREAD

**Issue by heinrich-ulbricht** [pnp/pnpcore#994] opened 2022-10-12 09:12 UTC
## Category

- [x] Bug

## Describe the bug

When creating a new list item getting more properties from the result `IListItem` fails.

This is surprising and feels like a bug. But I might also be me misunderstanding `EnsurePropertiesAsync`.

## Steps to reproduce

1. Create new list element using `Items.AddAsync`
2. Check the content of `Values` on the resulting list item reference - it contains one element, the `Title` value
3. `EnsurePropertiesAsync` the `Values` propery on the resulting item
4. Check the content of `Values` - it still only contains `Title` (UNEXPECTED)

Code to reproduce:

```
var item = await list.Items.AddAsync(new Dictionary<string, object?>
{
    { "Title", "Shiny new item" }
}).ConfigureAwait(false);
await item.EnsurePropertiesAsync(item => item.Values).ConfigureAwait(false);
```

A workaround is to request the list item again which then has 10 `Values` values like Modified etc. set:

```
var newListItem = await list.Items.GetByIdAsync(item.Id).ConfigureAwait(false);
```

I would have expected the same result from step 3 above.

## Expected behavior

In step 4 I expect the item's `Values` to contain more than the `Title`. `Modified` etc. should be there as well.

## Environment details (*development & target environment*)

I'm using the latest 1.7.0 _release_ and #961 applied. I currently don't have the environment with running nightly custom build and SharePoint connection. I searched the current issues with `EnsurePropertiesAsync` and nothing came up that looks like this issue, so I assume it's new. If this causes too much work on your part feel free to close, I just want to put it out here as reminder for myself and possibly others searching for issues with `EnsurePropertiesAsync`.

**Comment by jansenbe** [comment] 2022-10-13 09:01
@heinrich-ulbricht : `EnsurePropertiesAsync` indeed does not support loading `IListItem` values as the `Values` collection is coming via inheritance of `ExpandoBaseDataModel` and is considered loaded when present. For now I'm gonna close this one as "by design", but I've added clarification in the inline code comments so that you'll via intellisense that using it on `Values` will not work.

**Closed by jansenbe** 2022-10-13 09:01 UTC
Labels: question
