### ISSUE TITLE
I'm trying to add list items in a simple site.. but keep getting Invalid file name error:

### ISSUE THREAD

**Issue by erwinvanhunen** [pnp/pnpcore#312] opened 2021-01-29 15:16 UTC
I'm trying to add list items in a simple site.. but keep getting Invalid file name error:
```
$batch = New-PnPBatch
Add-PnPListItem -List $list -Values @{"Title" ="site1"} -Batch $batch
Add-PnPListItem -List $list -Values @{"Title" ="site2"} -Batch $batch
Add-PnPListItem -List $list -Values @{"Title" ="site3"} -Batch $batch   
$details= Invoke-PnPBatch -Batch $batch -Details

```
results in 

Invalid file name.
The file name you specified could not be used.  It may be the name of an existing file or directory, or you may not have permission to access the file.

I'm using
Manifest   1.2.0      PnP.PowerShell  
Tested with nightly build as well:
Manifest   1.2.7      PnP.PowerShell

Note: it works if I remove the batching.

_Originally posted by @bhishma in https://github.com/pnp/powershell/discussions/195_

**Comment by bhishma** [comment] 2021-01-30 23:58
Sorry for confusion. I meant to not show the real guid here that's why tried to obfuscate. 
The real error shows GUID properly.

**Comment by erwinvanhunen** [comment] 2021-01-31 10:48
Okay, that explains :-)

In our ongoing investigation, could you run the exact following snippet in a test site? 

```powershell
New-PnPList -Title "PnPTestList" -Template GenericList
$list = Get-PnPList -Identity "PnPTestList"
$batch = New-PnPBatch
1..5 | %{ Add-PnPListItem -List $list -Values @{"Title"="Title $_"} -Batch $batch }
Invoke-PnPBatch $batch -StopOnException
```

And see what happens? Just to determine if there is something with the list that makes it through the exception.

**Comment by bhishma** [comment] 2021-01-31 11:33
I still get same issue:
```


PS C:\Users\testUser> New-PnPList -Title "PnPTestList" -Template GenericList

Title       Id Url
-----       -- ---
PnPTestList


PS C:\Users\testUser> $list = Get-PnPList -Identity "PnPTestList"
PS C:\Users\testUser> $batch = New-PnPBatch
PS C:\Users\testUser> 1..5 | %{ Add-PnPListItem -List $list -Values @{"Title"="Title $_"} -Batch $batch }
PS C:\Users\testUser> Invoke-PnPBatch $batch -StopOnException
Invoke-PnPBatch : File Not Found.
At line:1 char:1
+ Invoke-PnPBatch $batch -StopOnException
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-PnPBatch], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Base.InvokeBatch

PS C:\Users\testUser> Get-PnPException


Message          : File Not Found.
Stacktrace       :    at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
                      at System.Management.Automation.CommandProcessor.ProcessRecord()
ScriptLineNumber : 1


```

**Comment by erwinvanhunen** [comment] 2021-01-31 11:49
I'm almost starting to wonder if the corporate proxy you mentioned is doing something in between. The main difference between using batching and non-batching is how we make the API calls behind the scenes. When adding an item without batching we use CSOM, when adding a item through batching we use the SharePoint REST api. 

Can you try to open this in your browser (where you obviously replace the url with actual tenant name and the id of the list)? You should receive an XML response.

```
https://domain.sharepoint.com/_api/Web/Lists(guid'9140-40f7-a84f-2e77da87e0d5')
```

Notice that the id component should be formatted as `guid'9a01c1fd-0c00-4acb-bcd4-9947e2047de5'`

**Comment by jansenbe** [comment] 2021-02-04 17:37
@bhishma : do you have an update to share?

**Comment by bhishma** [comment] 2021-02-05 00:51
I think Erwin is correct. Must be the proxy thing. I was able to execute same command outside of proxy. However I do get the XML response when I try to hit the endpoint with proxy too.

**Comment by erwinvanhunen** [comment] 2021-02-05 09:29
We would propose to exclude the SharePoint tenant from the proxy, but it unfortunately stops here for us as we cannot control your proxy.

**Comment by ollimenzel** [comment] 2021-05-10 06:34
I'm having the same problem, but I'm not sitting behind a proxy. I tried it with two different tenants, but it's failing for both.
Can someone please look at this agian?!

**Comment by rtonerii** [comment] 2021-06-01 19:42
> I'm having the same problem, but I'm not sitting behind a proxy. I tried it with two different tenants, but it's failing for both.
> Can someone please look at this again?!

I am having the same issue, and I a not behind a proxy either.

**Comment by DaleyKD** [comment] 2021-06-01 19:51
@ollimenzel and @rtonerii : Are you both using the PnP.PowerShell?  What version?

I can confirm that this works fine in PnP.Core via C#.

**Comment by ollimenzel** [comment] 2021-06-01 19:55
Hi in the meantime I opened a new report, and it was also reproduceable as you can see here:
https://github.com/pnp/powershell/issues/668
It seems to be a problem with the root SiteCollection in my case

**Comment by DaleyKD** [comment] 2021-06-01 20:33
@ollimenzel : That root Site Collection was definitely the piece I was missing.  I don't know if that's the same issue for @rtonerii  or not.  I've submitted a PR and will see if it's accepted by @jansenbe .

**Comment by DaleyKD** [comment] 2021-06-01 20:33
@ollimenzel : That root Site Collection was definitely the piece I was missing.  I don't know if that's the same issue for @rtonerii  or not.  I've submitted a PR and will see if it's accepted by @jansenbe .

**Comment by jansenbe** [comment] 2021-06-02 12:50
@DaleyKD : thanks for helping out and creating the PR
@ollimenzel / @rtonerii : I've merged the PR from @DaleyKD , this will be included in the tomorrow's nightly build from PnP PS, so would recommend giving that a try and let us know.

**Comment by rtonerii** [comment] 2021-06-03 18:47
> @DaleyKD : thanks for helping out and creating the PR
> @ollimenzel / @rtonerii : I've merged the PR from @DaleyKD , this will be included in the tomorrow's nightly build from PnP PS, so would recommend giving that a try and let us know.

I have been testing this on a sub-site collection.  I installed the latest from today and I am having other issues.

**Comment by DaleyKD** [comment] 2021-06-03 19:07
@rtonerii : Could you show me your full `Add-PnPListItem` command you're using?  (You can omit the tenant if you'd like.)

**Comment by rtonerii** [comment] 2021-06-03 19:57
@DaleyKD Here is the script.

`New-PnPList -Title "PnPTestList" -Template GenericList -ErrorAction SilentlyContinue
$list = Get-PnPList -Identity "PnPTestList"
$batch = New-PnPBatch
1..5 | %{ Add-PnPListItem -List $list -Values @{"Title"="Title $_"} -Batch $batch }
Invoke-PnPBatch $batch -Details -Debug`


I did some more testing and it works in a PowerShell console window but it errors in the VS Code development enviroment.

**Comment by jansenbe** [comment] 2021-06-03 20:36
Can you check the PS version where it works (and not works). You get the PS version via `$PSVersionTable`

**Comment by rtonerii** [comment] 2021-06-03 21:37
Name                           Value
----                           -----
PSVersion                      5.1.19041.906
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.906
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by rtonerii** [comment] 2021-06-03 21:38
> Can you check the PS version where it works (and not works). You get the PS version via `$PSVersionTable`

Name                           Value
----                           -----
PSVersion                      5.1.19041.906
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.906
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by jansenbe** [comment] 2021-06-04 07:25
so is the working version (PS console) or the non working version (VS Code)? I want to understand if there's a difference between those. PS version 5 uses .NET Framework while PS version 7+ uses .NET Core / .NET 5

**Comment by rtonerii** [comment] 2021-06-05 00:34
I can try both on monday.

**Comment by rtonerii** [comment] 2021-06-07 13:31
OK,
The issue only seems to be happening with Powershell 5.1, when using VS Code.

**Comment by rtonerii** [comment] 2021-06-07 15:28
OK, some more updates.
I updated my environments to version 1.6.0.

I am now able to successfully process the above script on both the root site and a sub-site collection with PS 7.1.

I am getting the following error on PS 5.1, **in VS Code**.
`Add-PnPListItem : Method not found: 'Int32 System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<Byte>)'`

Everything works with the regular PowerShell console windows.

**Comment by jansenbe** [comment] 2021-06-08 06:38
It seems as in the 5.1 console version of VS Code some other module is loaded first loading an older version of an assembly (possibly System.Text.Encodings.Web.dll)...when the PS module is loaded afterwards things fail. You could consider switching to PS7 in VS Code (https://rnelson0.com/2020/03/05/using-powershell-7-in-vs-code/). 

In general there's no easy fix for this as in PS world modules can easily load conflicting assemblies...best is to not load too many modules by default and then load the modules you need on demand.

**Closed by jansenbe** 2021-06-08 06:38 UTC
Labels: area: model 📐, question

**Comment by rtonerii** [comment] 2021-06-08 14:26
> It seems as in the 5.1 console version of VS Code some other module is loaded first loading an older version of an assembly (possibly System.Text.Encodings.Web.dll)...when the PS module is loaded afterwards things fail. You could consider switching to PS7 in VS Code (https://rnelson0.com/2020/03/05/using-powershell-7-in-vs-code/).
> 
> In general there's no easy fix for this as in PS world modules can easily load conflicting assemblies...best is to not load too many modules by default and then load the modules you need on demand.

Thanks,
I will try and make this work.

**Comment by Micael-stack** [comment] 2021-06-22 14:29
Pnp Powershell is really not working well with Ps 5.1. Switch to Ps7. 

With VsCode : 
![image](https://user-images.githubusercontent.com/52808567/122943104-bb630e00-d344-11eb-98d3-2c60509e0d29.png)
