### ISSUE TITLE
"Object reference not set to an instance of an object" on pnpContextFactory.CreateAsync(Uri)

### ISSUE THREAD

**Issue by SPDEVGUY** [pnp/pnpcore#623] opened 2021-11-13 00:30 UTC
## Category

- [x] Bug

## Describe the bug

Issue with pnp framework out of the box following start guide from SDK basics start guide:
https://pnp.github.io/pnpcore/using-the-sdk/readme.html

Using the multi-tenant PnP Azure AD application

![image](https://user-images.githubusercontent.com/3208188/141598338-6102c7d5-4cc2-4ce9-9a34-a31ea393c3e2.png)
![image](https://user-images.githubusercontent.com/3208188/141598355-436f6907-1dca-43f1-aed2-aba65ba95bc6.png)
Note - SitesToWork with is removed and Credentials section as well as I'm expecting to be using the PnP Azure AD application multi-tenant authorized app.

A very basic code test to try and get the root web's title.
![image](https://user-images.githubusercontent.com/3208188/141598319-718f8202-d0d9-4c1f-b57a-394cbbd3a595.png)
url provided is the root site of the SharePoint Site (example https://contoso.sharepoint.com)

## Steps to reproduce

1. Follow start guide.  Created a .NET 4.7.2 App, added nugets for PNP Core 1.4.0 and PnP.Core.Auth 1.4.0 super basic console app.

2. Authorize application using the example (changing contoso.onmicrosoft.com to my site url) https://login.microsoftonline.com/contoso.onmicrosoft.com/adminconsent?client_id=31359c7f-bd7e-475c-86db-fdb8c937548e&state=12345&redirect_uri=https://aka.ms/sppnp

3. See code above 

## Expected behavior

Should load the context if I'm understanding the documentation correctly, you can provide the site url into CreateAsync,
However instead of throwing any useful intelligent error it blows up with an object ref is null error.

## Environment details (*development & target environment*)

- **SDK version**: 1.4.0
- **OS**: Win 10
- **SDK used in**: Console App
- **Framework**: .NET 4.7.2
- **Browser(s)**: n/a
- **Tooling**: Visual Studio 2019
- **Additional details**:  Super basic, following the startup guide.  Trying to make a console app that can take a url provided by command line argument instead of in a configuration file and use the existing PNP azure ad app.

**Comment by SPDEVGUY** [comment] 2021-11-13 00:52
Used pnp powershell to confirm that the Azure AD tenant PNP App is registered, I think? 
![image](https://user-images.githubusercontent.com/3208188/141599231-4db80120-d2a3-4707-b06b-ad7ea7e35919.png)

**Comment by jansenbe** [comment] 2021-11-13 09:40
@SPDEVGUY , thanks for using PnP Core SDK and reporting this. I think the problem is that your config file is missing the authentication information. Can you add the `Credentials` section as shown in below json config example **or** configure auth using code. In both cases an interactive login is configured using the PnP Management Shell application.

```csharp
.ConfigureServices((hostingContext, services) =>
{                
    // Add the PnP Core SDK library services
    services.AddPnPCore();
    // Add the PnP Core SDK library services configuration from the appsettings.json file
    services.Configure<PnPCoreOptions>(hostingContext.Configuration.GetSection("PnPCore"));
    // Add the PnP Core SDK Authentication Providers
    services.AddPnPCoreAuthentication(options =>
    {
        options.Credentials.Configurations.Add("Default", new PnPCoreAuthenticationCredentialConfigurationOptions() 
        { 
            Interactive = new PnPCoreAuthenticationInteractiveOptions(),
        });
        options.Credentials.DefaultConfiguration = "Default";
    });
})
```

```json
{
  "PnPCore": {
    "DisableTelemetry": "false",
    "HttpRequests": {
      "UserAgent": "ISV|Contoso|ProductX",
      "Timeout": "100",
      "SharePointRest": {
        "UseRetryAfterHeader": "false",
        "MaxRetries": "10",
        "DelayInSeconds": "3",
        "UseIncrementalDelay": "true"
      },
      "MicrosoftGraph": {
        "UseRetryAfterHeader": "true",
        "MaxRetries": "10",
        "DelayInSeconds": "3",
        "UseIncrementalDelay": "true"
      }
    },
    "PnPContext": {
      "GraphFirst": "true",
      "GraphCanUseBeta": "true",
      "GraphAlwaysUseBeta": "false"
    } ,
    "Credentials": {
      "DefaultConfiguration": "myTestConfiguration",
      "Configurations": {
        "myTestConfiguration": {
          "Interactive": {
            "RedirectUri": "http://localhost"
          }
        }
      }
    }
  },
  "Logging": {
    "LogLevel": {
      "Default": "Debug"
    }
  }
}
```

**Comment by SPDEVGUY** [comment] 2021-11-13 16:32
That got it!

Line 44 of https://github.com/pnp/pnpcore/blob/32741430a3fb8d1c3f9e163477acb473024b152b/src/sdk/PnP.Core/Services/Core/PnPContextFactory.cs
`
            initializeAuthenticationProvider?.Invoke(configuration.AuthenticationProvider);
`

Should check for [configuration.AuthenticationProvider == null] and report it adequately, or use a default Azure AD setup one.

As a total noob to the framework I had no idea what was going on. 

The documentation could maybe be enhanced to provide a specific example of using the azure ad mode  I think it was there as a side note:
`
If you don't want to register a custom app in your target Azure Active Directory, you can skip the ClientId and TenantId properties and the PnP Core SDK will rely on a multi-tenant application that will be registered on your tenant, upon admin consent.
`

But it may be more clear to provide an actual example as I interpreted that as the software would just use a default authentication provider if one wasn't provided.

**Comment by jansenbe** [comment] 2021-11-13 21:54
Good point about throwing a better exception when there's no auth provider setup when a `PnPContext` is created.

We plan to make some getting started video/tutorials which will help with a better first run experience.

**Comment by jansenbe** [comment] 2021-11-14 09:11
@SPDEVGUY : input validation is done. Getting started content will arrive in the coming weeks. Will close this issue now.

**Closed by jansenbe** 2021-11-14 09:11 UTC
Labels: question
