### ISSUE TITLE
The web being updated was changed by an external process.

### ISSUE THREAD

**Issue by mohammadamer** [pnp/pnpcore#1106] opened 2023-02-20 16:13 UTC
## Category

- [x] Bug

## Describe the bug
The bug is in two places in our solution Azure Functions where in the first one we hide the title of the site and the second we enable or disable multilanguage feature in a site.

```
Result: Failure
Exception: System.AggregateException: One or more errors occurred. (SharePoint Rest service exception)
 ---> HttpResponseCode: 500
Code: Microsoft.SharePoint.SPException
Message: The web being updated was changed by an external process.
ClientRequestId: 311498a0-80b9-6000-1ca6-fcc25e358feb
SPClientServiceRequestDuration: 30
X-SharePointHealthScore: 1
X-SP-SERVERSTATE: ReadOnly=0


PnP.Core.SharePointRestServiceException: SharePoint Rest service exception
   at PnP.Core.Services.BatchClient.ExecuteSharePointRestInteractiveAsync(Batch batch)
   at PnP.Core.Services.BatchClient.ExecuteSharePointRestBatchAsync(Batch batch)
   at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch)
   at PnP.Core.Model.BaseDataModel`1.BaseUpdate(Func`2 fromJsonCasting, Action`1 postMappingJson)
   at PnP.Core.Model.BaseDataModel`1.UpdateAsync()
   at Functions.DisableMultilingual.Run(String url, String environmentContents) in

 D:\a\1\s\Functions\DisableMultilingual.cs:line 40

   at Microsoft.Azure.Functions.Worker.Invocation.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in
 D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\VoidTaskMethodInvoker.cs:line 24
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in

 D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in
 D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
   at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 16
   at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider, IInputConversionFeatureProvider functionInputConversionFeatureProvider) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 199
Stack:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in

 D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in

 D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
   at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next)
 in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 16
   at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request,
 IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer,
 IOutputBindingsInfoProvider outputBindingsInfoProvider, IInputConversionFeatureProvider functionInputConversionFeatureProvider) 
in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 199
```

## Steps to reproduce

1. See code `code...` 

  ```
  [Function("HideTitle")]
        public async Task Run([QueueTrigger("hide-title")] string url)
        {
            var ctx = await Factory.CreateAsync(new Uri(url));
            ctx.Web.HideTitleInHeader = true;
            await ctx.Web.UpdateAsync();
        }
```

2. See code `code...` 

```
      [Function("DisableMultilingual")]
        public async Task Run([QueueTrigger("multilingual")] string url)
        {
            var ctx = await Factory.CreateAsync(new Uri(url));
            var web = await ctx.Web.GetAsync(w => w.IsMultilingual);
            web.IsMultilingual = false;
            await web.UpdateAsync();
        }
```

## Expected behavior
Expected behavior is to enable or disable site multilanguage without issues. The same for hiding the site title.

## Environment details (*development & target environment*)

- **SDK version**: [PnP.Core Version="1.7.0" ]
- **OS**: [Windows 10]
- **Framework**: [Azure Function runtime v4 | .NET Core v6]
- **Browser(s)**: [ Chrome | Chromium Edge]
- **Tooling**: [Visual Studio 2022]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

### Additional context
Additional context for this case is that we are running these azure functions heavily for many sites using Azure Queue trigger.

**Comment by jansenbe** [comment] 2023-02-21 07:12
@mohammadamer : this feels like a SharePoint issue, but will do some testing. What permissions does your app have?

**Comment by mohammadamer** [comment] 2023-02-21 08:57
Hi @jansenbe 

I had a look at the app insights, and it seems that such errors are happening consistently.

Also found:

```
Result: Failure
Exception: System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
```

**The app permissions:**
MS Graph
Sites.FullControl.All
Sites.Manage.All
Sites.Read.All
Sites.ReadWrite.All

MS SharePoint
Sites.FullControl.All
TermStore.ReadWrite.All

**Comment by jansenbe** [comment] 2023-02-21 09:42
@mohammadamer : I just tried below 2 snippets and they work as expected. So the issue is coming from elsewhere or due to other conditions. Some things to consider:
- Are there parallel operations ongoing using the same context?
- When you leave out this update, do the other operations then work?
- Is there something specific for the impacted site? Maybe try with a newly created site? Different site templates?


![image](https://user-images.githubusercontent.com/7451219/220307121-87ee2766-fc48-4a26-9e38-b4308ace7de6.png)


![image](https://user-images.githubusercontent.com/7451219/220307224-d47fa8f7-65b8-4cec-9fd4-a4f94266e2e0.png)

**Comment by mohammadamer** [comment] 2023-02-21 10:09
@jansenbe 
Yes, there are parallel operations (Azure Functions) ongoing that are using different instances of the PnPContext and updating the same site or different sites with the same APP registration.
The other operations are working but some others are failing.

I'm thinking that this might be throttling because we are doing many stuffs using different Azure functions that are using the same APP registration.

**Comment by mohammadamer** [comment] 2023-02-21 11:33
@jansenbe 
Okay, that might be the issue If both functions run in parallel against the same web.
I'll do another test and check errors again Today. If it happens again then I'll think about combine both functions as they both are updating the Web.

**Comment by jansenbe** [comment] 2023-02-21 12:12
I'm going to close this issue @mohammadamer as it's not an issue inside PnP Core SDK. Feel free to re-open or create a new one if you've information that points to a bug in PnP Core SDK.

**Closed by jansenbe** 2023-02-21 12:12 UTC
Labels: question, area: model 📐
