### ISSUE TITLE
ISite.JoinHubSiteAsync not functional for multi-geo

### ISSUE THREAD

**Issue by ohaak2** [pnp/pnpcore#734] opened 2022-01-28 11:07 UTC
## Category

- [x] Bug

## Describe the bug

Trying to join a mulit-geo site to a hubsite using ISite.JoinHubSiteAsync fails with error "Proxy request for hubsite GetById failed with following error: The remote server returned an error: (401) Unauthorized."

## Steps to reproduce

```csharp
using (var context = await pnpContextFactory.CreateAsync("SiteToWorkWith"))
{
    var site = context.site;
    result = await site.JoinHubSiteAsync("HubSiteId");
}
```

## Expected behavior

Site should be associated to the hub site.

## Environment details (*development & target environment*)

- **SDK version**: 1.5.42-nightly
- **OS**: Windows 11
- **SDK used in**: Console App
- **Framework**:  .NET Core v6.x 
- **Browser(s)**: no browser involved
- **Tooling**: Visual Studio 2022
- **Additional details**: using app-only context for authentication

### Additional context

The reported error is from my point of view not PnP.Core specific. I'll get the same error using PnP.PowerShell using the PnP.Framwork functionality under the hood.

Another interesting point might be that it doen't matter for the outcome here, if both - site to be associated and the hub site - are located in the same geo-location or not.

It's worth mentioning, that the code normally has sufficient permissions to access both sites and that such an operation works without fuzz if we are handling sites in central location.

**Comment by jansenbe** [comment] 2022-02-01 17:07
@ohaak2 : so joining a hub site in the main location works, but doing the same in a geo location fails?

**Comment by ohaak2** [comment] 2022-02-01 17:18
@jansenbe Neither the PnP.Core approach, nor the one used under the hood in PnP.PowerShell is working. Im currently trying one last approach using the SP REST API ...

**Comment by ohaak2** [comment] 2022-02-01 17:54
@jansenbe Ok, same situation for using SharePoint api. It all works out smooth as long as neither the site to be associated nor the hub site involved are using a geo-location. This is the api response:
```json
{"odata.metadata":"https://draeger.sharepoint.com/sites/olru-2022-02-01-geolocation-test-1/_api/$metadata#Edm.Null","odata.null":true}
```

Otherwise I will get an error:
```json
{"odata.error":{"code":"-1, System.Exception","message":{"lang":"de-DE","value":"Proxy request for hubsite GetById failed with following error: The remote server returned an error: (401) Unauthorized."}}}
```

For authentication I was using the site scope of the site to be associcated:
```csharp
string siteUrl = "https://my-tenant.sharepoint.com/sites/some-site";
var uri = new Uri(siteUrl);
var scopes = new[] { $"{uri.Scheme}://{uri.Authority}/.default" };
```

Method to get the access token is using PnP.Framework.AuthenticationManager with and app-only context
```csharp
public static async Task<string> GetAuthTokenAsync(string clientId, string thumbPrint, string tenantId, string[] scopes)
{
    var authManager = AuthenticationManager.CreateWithCertificate(clientId, StoreName.My, StoreLocation.CurrentUser, thumbPrint, $"{tenantId}.onmicrosoft.com");
    string token = await authManager.GetAccessTokenAsync(scopes);

    return token;
}
```

Calling the SharPoint api like this:

```csharp
private async Task<bool> AddSiteToHubSiteAsync(string SiteUrl, string HubSiteUrl, string token)
{
    bool result = false;
    try
    {
        Logger.WriteLine($"[AddSiteToHubSiteAsync] Add site '{SiteUrl}' to hub site '{HubSiteUrl}' ...");

        using PnPContext hubContext = GetPnPContext(HubSiteUrl);
        ISite hubSite = hubContext.Site;

        string apiUrl = $"{SiteUrl}/_api/site/JoinHubSite('{hubSite.Id}')";

        using (var request = new HttpRequestMessage(HttpMethod.Post, apiUrl))
        {
            request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);

            // send request
            var response = await client.SendAsync(request);

            string details = await response.Content.ReadAsStringAsync();
            if (!details.IsNullOrEmpty())
            {
                Logger.WriteLine($"[AddSiteToHubSiteAsync] Response details: '{details}'");
            }

            // check response
            response.EnsureSuccessStatusCode();

            result = true;

            Logger.WriteLine($"[AddSiteToHubSiteAsync] Site '{SiteUrl}' successfully associated to hub site '{HubSiteUrl}'.");
        }
    }
    catch (Exception ex)
    {
        Logger.WriteLine($"[AddSiteToHubSiteAsync] ERROR: An error occurred associating site '{SiteUrl}' to hub site '{HubSiteUrl}': {ex.Message}");
    }

    return result;
}
```

**Comment by jansenbe** [comment] 2022-02-01 18:01
Thanks for the detailed analysis @ohaak2 , seems like a bug. I'll follow-up internally.

**Comment by jansenbe** [comment] 2022-02-01 19:10
@ohaak2 : can you try with delegated permissions as well. I checked our code base and seems like "by design". This operation will request hub site information across geo's and that's not supported with app-only currently.

**Comment by ohaak2** [comment] 2022-02-02 12:25
@jansenbe Sad to hear that. It's always troublesome that a lot of important provsioning task still need to have delegate permissions.

In other scenarios we are handling this with delegate permission using a service user  (e. g. add sensitivity label to a group), but in that case we don't need a service user with specific permission rights. We are just adding a fairly permission-less service account to the group's owners first, perform the delegate permission task (using this service user) and finally remove the account afterwards from the group's owners. A lot of trouble for an otherwise simple task, but it works fine.

That's however no valid scenario for handling the hub site association, as this would (I guess) require SP admin permission on the tenant ...

For giving you feedback on using the delegate permission I will have to use the PowerShell Cmdlet 'Add-PnPHubSiteAssociation', as our app reg in the multi-geo tenant doesn't have a reply url configured and we won't get that changed short-term. I hope testing outcome for that has enough relevance for our question ...

**Comment by ohaak2** [comment] 2022-02-02 14:40
@jansenbe Ok - found a better option to check this using PnP.Powershell. Using "interactive" login and thus working with a user context I was able to associate a site with geo-location to a hub site in central. The user whose context I was using was effectivly site owner and site adminstrator by being an owner of the site's M365 group.

```powershell
❯ Invoke-PnPSPRestMethod -Method POST -Url "/_api/site/JoinHubSite('d2829624-04bc-493f-a4ef-9036978ebf99')" -Content ""

odata.null
----------
      True
```

I'll try to build up a test case to use the afrormention service user scenario we've already used for setting sensitivity labels to a group and hopefully it works out the same way.

One more question: If the code base is checking hub site info across the hubs, if using GetHubSiteById, is that also the case if we try to resolve the hub site by url? It definitely doesn't feel consistent, if the command is doing fine "app-only" with "central" site, but fails for geo-location sites. So maybe just a change from the ById to ByUrl method could solve the issue for the higher level apis.

**Comment by jansenbe** [comment] 2022-02-02 18:07
@ohaak2 , good to know it at least works with delegated permissions. What you want would be an internal change, and I think would result in the same issues. As this issue is not something PnP Core SDK can solve I'm gonna close this case. I'll add a note to our docs to indicate that joining/unjoining hub sites has these limitations.

**Closed by jansenbe** 2022-02-02 18:07 UTC
Labels: question, area: model 📐
