### ISSUE TITLE
GetByIdAsync fails when taxonomy field empty

### ISSUE THREAD

**Issue by dgtheninja** [pnp/pnpcore#504] opened 2021-06-29 12:17 UTC
## Category

- [x] Bug

## Describe the bug

I have a document library with a taxonomy field, which is optional and several items do not have a value. When I call the library.Items.GetByIdAsync method it fails on the items where the taxonomy field is not set with a System.InvalidOperationException, with the message "The requested operation requires an element of type 'String', but the target element has type 'Null'."

If I enter a value for the taxonomy field it works as expected.

## Steps to reproduce

here is my code
```
var library = await pnpContext.Web.Lists.GetByTitleAsync(libraryTitle);

var libraryItem = await library.Items.GetByIdAsync(item, i => i.All, i => i.File);
```

## Expected behavior

The call should succeed no matter whether there is a value for the taxonomy field

## Environment details (*development & target environment*)

- **SDK version**: 1.2
- **OS**: Windows Server 2016
- **SDK used in**: ASP.Net Web app
- **Framework**: .NET 5
- **Browser(s)**: Chrome v91
- **Tooling**: Visual Studio 2019

### Additional context

Stack trace is
```
System.InvalidOperationException:
   at System.Text.Json.JsonDocument.TryGetValue (System.Text.Json, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)
   at System.Text.Json.JsonElement.GetGuid (System.Text.Json, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)
   at PnP.Core.Model.SharePoint.FieldTaxonomyValue.FromJson (PnP.Core, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null)
   at PnP.Core.Services.JsonMappingHelper.ProcessSpecialRestFieldType (PnP.Core, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null)
   at PnP.Core.Services.JsonMappingHelper+<FromJsonRest>d__2.MoveNext (PnP.Core, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at PnP.Core.Services.JsonMappingHelper+<FromJson>d__1.MoveNext (PnP.Core, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at PnP.Core.Model.BaseDataModel`1+<ProcessResponseAsync>d__18.MoveNext (PnP.Core, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at PnP.Core.Services.JsonMappingHelper+<FromJsonRest>d__2.MoveNext (PnP.Core, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at PnP.Core.Services.JsonMappingHelper+<FromJson>d__1.MoveNext (PnP.Core, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at PnP.Core.Services.JsonMappingHelper+<MapJsonToModel>d__0.MoveNext (PnP.Core, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at PnP.Core.Services.BatchClient+<ProcessSharePointRestBatchResponse>d__48.MoveNext (PnP.Core, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at PnP.Core.Services.BatchClient+<ExecuteSharePointRestBatchAsync>d__46.MoveNext (PnP.Core, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at PnP.Core.Services.BatchClient+<ExecuteBatch>d__36.MoveNext (PnP.Core, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at PnP.Core.Services.PnPContext+<ExecuteAsync>d__66.MoveNext (PnP.Core, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at PnP.Core.QueryModel.DataModelQueryService`1+<ExecuteQueryAsync>d__16.MoveNext (PnP.Core, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at PnP.Core.QueryModel.BaseQueryProvider+<CastTask>d__10`1.MoveNext (PnP.Core, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at PnP.Core.Model.SharePoint.ListItemCollection+<GetByIdAsync>d__10.MoveNext (PnP.Core, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at TVPHC.M365.ForceFiles.App.Repositories.SharePointRepository+<MoveFiles>d__9.MoveNext (TVPHC.M365.ForceFiles.App, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullTVPHC.M365.ForceFiles.App, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: D:\a\1\s\TVPHC.M365.ForceFiles.App\TVPHC.M365.ForceFiles.App\Repositories\SharePointRepository.csTVPHC.M365.ForceFiles.App, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 268)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at TVPHC.M365.ForceFiles.App.Services.FileCenterService+<MoveFiles>d__10.MoveNext (TVPHC.M365.ForceFiles.App, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullTVPHC.M365.ForceFiles.App, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: D:\a\1\s\TVPHC.M365.ForceFiles.App\TVPHC.M365.ForceFiles.App\Services\FileCenterService.csTVPHC.M365.ForceFiles.App, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 173)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at TVPHC.M365.ForceFiles.App.Controllers.SiteController+<MoveFiles>d__7.MoveNext (TVPHC.M365.ForceFiles.App, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullTVPHC.M365.ForceFiles.App, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: D:\a\1\s\TVPHC.M365.ForceFiles.App\TVPHC.M365.ForceFiles.App\Controllers\SiteController.csTVPHC.M365.ForceFiles.App, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 171)

```

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment] 2021-06-29 18:57
Good catch, I'll have a look and fix it

**Comment by jansenbe** [comment] 2021-06-30 06:45
@dgtheninja : I'm not able to reproduce the issue (tried with below test case), but the stack trace and error are quite clear, seems that for some reason you're getting JSON data that has a null value for the term id. I've added additional checks on the JsonElement kind (object, not null) before trying to get the actual value from the element. This should prevent the errors you see. Would be good if you could give tomorrow's nightly build a try.

Test case that's not simulating the issue:
```csharp
[TestMethod]
public async Task EmptyTaxonomyFieldReadTest()
{
    TestCommon.Instance.Mocking = false;
    using (var context = await TestCommon.Instance.GetContextAsync(TestCommon.TestSite))
    {
        // Taxonomy data ~ replace by creating term set once taxonomy APIs work again
        Guid termStore = new Guid("437b86fc-1258-45a9-85ea-87a29156ce3c");
        Guid termSet = new Guid("d50ec969-cb27-4a49-839f-3c25d1d607d5");
        Guid term1 = new Guid("108b34b1-87af-452d-be13-881a29477965");

        //==========================================================
        // Step 1: Create a new list
        string listTitle = TestCommon.GetPnPSdkTestAssetName("EmptyTaxonomyFieldReadTest");
        var myList = await context.Web.Lists.GetByTitleAsync(listTitle);

        if (TestCommon.Instance.Mocking && myList != null)
        {
            Assert.Inconclusive("Test data set should be setup to not have the list available.");
        }

        if (myList == null)
        {
            myList = await context.Web.Lists.AddAsync(listTitle, ListTemplateType.GenericList);
        }

        //==========================================================
        // Step 2: Add special fields
        string fieldGroup = "TEST GROUP";

        // Taxonomy field 1
        string fldTaxonomy1 = "TaxonomyField1";
        IField addedTaxonomyField1 = await myList.Fields.AddTaxonomyAsync(fldTaxonomy1, new FieldTaxonomyOptions()
        {
            Group = fieldGroup,
            AddToDefaultView = true,
            TermStoreId = termStore,
            TermSetId = termSet
        });

        // Taxonomy Multi field 1
        string fldTaxonomyMulti1 = "TaxonomyMultiField1";
        IField addedTaxonomyMultiField1 = await myList.Fields.AddTaxonomyMultiAsync(fldTaxonomyMulti1, new FieldTaxonomyOptions()
        {
            Group = fieldGroup,
            AddToDefaultView = true,
            TermStoreId = termStore,
            TermSetId = termSet
        });

        //==========================================================
        // Step 3: Add a list item
        Dictionary<string, object> item = new Dictionary<string, object>()
        {
            { "Title", "Item1" }
        };

        // Add the configured list item
        var addedItem = await myList.Items.AddAsync(item);

        // Load the item via getbyid
        var loadedItem = await myList.Items.GetByIdAsync(1, i => i.All, i => i.File);

        Assert.IsTrue(loadedItem.Title == "Item1");

        await myList.DeleteAsync();

    }
}
```

**Comment by jansenbe** [comment] 2021-06-30 06:48
@dgtheninja : I'm closing the issue now, but feel free to re-open if you still experience issues with the nightly builds as of July 1st.

**Closed by jansenbe** 2021-06-30 06:48 UTC
Labels: area: model 📐, bug

**Comment by dgtheninja** [comment] 2021-07-12 08:44
Thanks @jansenbe, I'm not seeing the issue with the latest nightly builds
