### ISSUE TITLE
Listitem UpdateAsync is failing without an error

### ISSUE THREAD

**Issue by SuleymanA** [pnp/pnpcore#1162] opened 2023-04-14 06:11 UTC
I noticed that UpdateAsync failes without an error when updating a multiuser field with a user that no longer exists. 

Strangly the user can still be ensured and I don't see any values in the user object that indicate it as inactive. The user was previously assigned on the site so already in the userinformation list.  

Ensuring: 
```
pnpContext.Web.EnsureUserBatch(batch, userName)
await pnpContext.ExecuteAsync(batch, true);  
```

List and required fields are loaded for updating:

```
IField inputProvidersField = allProductRolesList.Fields.AsRequested().First(f => f.InternalName == Constants.AllProductRolesFields.InputProviders);
IField inputApproversField = allProductRolesList.Fields.AsRequested().First(f => f.InternalName == Constants.AllProductRolesFields.InputApprovers);

var providersCollection = inputProvidersField.NewFieldValueCollection();
var approversCollection = inputApproversField.NewFieldValueCollection();
```

Multi user field populated like this:
`providersCollection.Values.Add(inputProvidersField.NewFieldUserValue(ensuredUsers[x]);`

Loading and updating the list item:

```
            var output = await allProductRolesList.LoadListDataAsStreamAsync(new RenderListDataOptions()
            {
                ViewXml = viewXml,
                RenderOptions = RenderListDataOptionsFlags.ListData
            });

            var currentRolesItem = allProductRolesList.Items.AsRequested().FirstOrDefault();
            if (currentRolesItem != null)
            {
                currentRolesItem.Values[Constants.AllProductRolesFields.UserToRole] = Newtonsoft.Json.JsonConvert.SerializeObject(userToRoles);
                currentRolesItem.Values[Constants.AllProductRolesFields.InputProviders] = providersCollection;
                currentRolesItem.Values[Constants.AllProductRolesFields.InputApprovers] = approversCollection;

                await currentRolesItem.UpdateAsync();
            }
```

Update executes without any error but the listitem is not updated. We noticed this only when we try to update the user field with a user that no longer can be resolved in the people picker (inactive/removed). When I use the same data for adding a new item to the list (await allProductRolesList.Items.AddAsync(values);) it throws an error saying that the people field could not be updated. 

I am using version 1.7.0.

Thanks in advance for the help!!

**Comment by jansenbe** [comment] 2023-04-14 18:04
@SuleymanA : what you see is expected when a user does not exist anymore. Once a user was "ensured" it stays like that and `EnsureUser` will return fine even if the user was removed from Azure AD. To support the scenario of setting/updating user fields we've added (in version 1.9) additional methods that validate a list of users: https://pnp.github.io/pnpcore/using-the-sdk/security-users.html#validating-users.

**Comment by SuleymanA** [comment] 2023-04-17 10:29
@jansenbe thanks for the suggestion! I have build similar user validation by looking up user through graph API. 

Is it expected behavior from SPO/PNP that updating a list item with invalid people values doesnt throw an error and also doesnt update the item? I have build checks to prevent this from happing but I expected that it throws an error just like with adding an item.

**Comment by jansenbe** [comment] 2023-04-17 11:58
@SuleymanA : I think this is by design as we're not doing anything special. You can try if the `SystemUpdate` methods work differently as they under the covers use a CSOM operation (as there are no REST systemupdate methods)

**Comment by jansenbe** [comment] 2023-04-19 06:55
@SuleymanA : think we can close this one?

**Comment by jansenbe** [comment] 2023-04-21 07:42
Closing per no more feedback

**Closed by jansenbe** 2023-04-21 07:42 UTC
Labels: question

**Comment by SuleymanA** [comment] 2023-04-21 08:23
Thx for your help!!
