### ISSUE TITLE
Cannot connect group to site

### ISSUE THREAD

**Issue by frodale** [pnp/pnpcore#1000] opened 2022-10-20 12:35 UTC
## Category

- [x] Bug

## Describe the bug

When 'Site creation' settings are as follow:

![image](https://user-images.githubusercontent.com/10073661/196949402-9bd84aaf-64b3-4dd7-9eb6-d9661958c3f3.png)

And trying to connect a group to a site using the following code:

ConnectSiteToGroupOptions groupConnectOptions = new ConnectSiteToGroupOptions(
    new Uri("https://contoso.sharepoint.com/sites/sitetogroupconnect"), 
    "sitealias", 
    "Site title");
await context.GetSiteCollectionManager().ConnectSiteCollectionToGroupAsync(groupConnectOptions);

I'm getting the following error:

HttpResponseCode: 500 Code: Microsoft.SharePoint.SPException Message: Modern site creation is not allowed. Contact your administrator for more information. ClientRequestId: eb7670a0-8086-5000-8f51-4764e8f75110 SPClientServiceRequestDuration: 142 X-SharePointHealthScore: 2 X-SP-SERVERSTATE: ReadOnly=0 PnP.Core.SharePointRestServiceException: SharePoint Rest service exception at PnP.Core.Services.BatchClient.ExecuteSharePointRestInteractiveAsync(Batch batch) at PnP.Core.Services.BatchClient.ExecuteSharePointRestBatchAsync(Batch batch) at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch) at PnP.Core.Model.BaseDataModel`1.RequestAsync(ApiCall apiCall, HttpMethod method, String operationName) at PnP.Core.Model.BaseDataModel`1.RawRequestAsync(ApiCall apiCall, HttpMethod method, String operationName) at PnP.Core.Admin.Model.SharePoint.SiteCollectionCreator.CreateSiteUsingSpoRestImplementationAsync(PnPContext context, SiteCreationModel siteCreationModel, Dictionary`2 payload, SiteCreationOptions creationOptions) at PnP.Core.Admin.Model.SharePoint.SiteCollectionCreator.ConnectGroupToSiteAsync(PnPContext contextIn, ConnectSiteToGroupOptions siteToGroupify, CreationOptions creationOptions) at PnP.Core.Admin.Model.SharePoint.SiteCollectionManager.ConnectSiteCollectionToGroupAsync(ConnectSiteToGroupOptions siteGroupConnectOptions, CreationOptions creationOptions)

This works fine when both 'checkboxes' are marked in the 'Site creation' settings page

**Comment by frodale** [comment] 2022-10-20 16:07
Thanks for the quick response, i was suspecting that, as i found that both the 
/_api/groupsitemanager/creategroupforsite
and 
_api/groupsitemanager/creategroupex
are failing with the same error

Thanks for the help, i hope it gets fixed quickly!

Best regards

**Comment by jansenbe** [comment] 2022-10-20 16:34
@frodale : what permissions does the user account you try this with have? Or are you trying using application permissions?

**Comment by frodale** [comment] 2022-10-20 18:31
the app registration has the following...

<img width="691" alt="image" src="https://user-images.githubusercontent.com/10073661/197029251-f74ace64-9848-4dd2-afd1-c62fcaebe3f5.png">

while the test user is a normal user

I will try with the user with sp admin role...

**Comment by frodale** [comment] 2022-10-20 19:15
Update: with a test user with Sharepoint Admin role, it works

**Comment by jansenbe** [comment] 2022-10-21 07:11
@frodale : the user has also be site collection admin to make groupify work

**Comment by frodale** [comment] 2022-10-21 07:20
Hello, when using the following settings

<img width="423" alt="image" src="https://user-images.githubusercontent.com/10073661/197136632-b113aa78-5d23-48e6-89e5-12a6d7a910e8.png">

It works with a normal user

**Comment by jansenbe** [comment] 2022-10-21 08:07
@frodale : I've been chatting with the feature owner as what you is by design...when not both boxes are checked there's an extra validation layer and for group connect that implies the user triggering the group connect must be site collection admin of the site. We're looking into updating docs to clarify this. In the meanwhile, I'll update the PnP Core SDK docs to clarify this requirement. Given PnP Core SDK can't change this behavior I'm going to close this issue.

Thanks for using PnP Core SDK and providing the feedback.

**Closed by jansenbe** 2022-10-21 08:07 UTC
Labels: question

**Comment by frodale** [comment] 2022-10-21 08:12
Hello again, the user is site collection admin, but still doesn't work, tested as well from the UI

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/10073661/197146851-bc659204-4080-41d7-aef8-87919f03c8c6.png">

**Comment by jansenbe** [comment] 2022-10-21 08:14
@frodale :Hmm, so only tenant admin then works?

**Comment by jansenbe** [comment] 2022-10-21 08:14
let me cross check then

**Comment by frodale** [comment] 2022-10-21 08:15
Thanks!

**Comment by jansenbe** [comment] 2022-10-21 08:22
I wrongly interpreted "admin" in the feedback I got, indeed this means SharePoint/tenant admin. The fact that the UI is still showing the groupify option to users is a bug which we'll track for getting fixed.

So, not immediately a solution for your problem I'm afraid.

**Comment by frodale** [comment] 2022-10-21 08:25
Ok, so to summarize:

1) If only the 1st checkbox is on, the only way to groupify a site is if the user is a Sharepoint Admin
2) If both the checkboxes are on, you need to be a site collection admin

correct?

**Comment by jansenbe** [comment] 2022-10-21 08:33
@frodale : correct

**Comment by frodale** [comment] 2022-10-21 08:38
ok, thanks for the clarification, the text itself in the 'Site creation' settings is not understandable

It will be nice to have a clear documentation of what it means

Thanks!
