### ISSUE TITLE
GetPermissionRequestsAsync() returns a request object that was already approved

### ISSUE THREAD

**Issue by larry-lau** [pnp/pnpcore#1197] opened 2023-06-02 18:18 UTC
## Category

- [x] Bug

## Describe the bug

The GetPermissionRequestsAsync() returns a request object that was already approved and if you
call ApprovePermissionRequestAsync to approve on the request id, you will get the following error message.

```
Error: An OAuth permission with the resource Microsoft Graph and scope User.Read already exists.
Parameter name: permissionRequest

```

if you navigate to the API Access page in Admin center, GetPermissionRequestsAsync() method will not return the request. it appears something happen on the API Access page that remove the permission request.

## Steps to reproduce
Attention: DO NOT navigate to the API Access page in SharePoint Admin Center between step 4 and step 6.

1. Deploy an app that requires "Microsoft Graph > User.Read" permission.
2. Approve the User.Read permission request.
3. Retract the app
4. Redeploy the app
5. GetPermissionRequestsAsync() and you will get
```
[
  {
    "Id": "xxxxx-xxx-xxxx-xxx-xxxxxxx",
    "Resource": "Microsoft Graph",
    "ResourceId": "Microsoft Graph",
    "Scope": "User.Read"
  }
]

```
6. Call ApprovePermissionRequestAsync  to approve --id <the request id in step 5>
```
Error: An OAuth permission with the resource Microsoft Graph and scope User.Read already exists.
Parameter name: permissionRequest
```

## Expected behavior

Step 5 should not return any permission request since the permission was already approved in step 2.

## Environment details (*development & target environment*)
- **SDK version**: [1.9.0]
- **OS**: [Windows 10]
- **SDK used in**: [ASP.Net Web app]
- **Framework**: [.NET 7]
- **Browser(s)**: [Not relevant]
- **Tooling**: [Visual Studio 2022]

### Additional context

This issue was fixed in the m365 cli but not in pnpcore yet [https://github.com/pnp/cli-microsoft365/issues/4671](https://github.com/pnp/cli-microsoft365/issues/4671)

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment] 2023-06-03 08:42
@larry-lau : I think the API works like the admin center works, when you deploy an app requiring a permission that was already granted that request still get's added for approval although technically this is not needed anymore. Thanks for listing the CLI fix, this indeed makes sense to have an improved experience. 

Tagging @mloitzl  to check if he like to take this one? No worries if not, but since you wrote the original code I thought you might be interested.

**Comment by mloitzl** [comment] 2023-06-03 11:51
@jansenbe Thanks for letting me know, indeed I am interested.
I'll have a look into it 🤓

**Comment by jansenbe** [comment] 2023-06-14 12:48
@mloitzl : thanks a ton for the fix, I've just tested and merged that one.

@larry-lau : please try again with the upcoming nightly build. 

Will close this issue now, please re-open or create a new one if the problem is not solved.

**Closed by jansenbe** 2023-06-14 12:48 UTC
Labels: area:admin 📜
