### ISSUE TITLE
IFile GetContentAsync or GetContent not getting more than 102kb

### ISSUE THREAD

**Issue by lynath** [pnp/pnpcore#1068] opened 2023-01-06 13:16 UTC
## Category

- [x] Bug

## Describe the bug

Cannot a download a file of size 100MB from SharePoint using IFile GetContent. The stream is not downloading more than 102kb.
I am trying to do this in Azure function v4 isolated process. The behavior is same in non-isolated process.

## Steps to reproduce

public async Task<HttpResponseData> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequestData req)
        {
            HttpResponseData response = null;
            _logger.LogInformation("GetSiteDocuments()");
            using (var pnpContext = await pnpContextFactory.CreateAsync("Default"))
            {
                _logger.LogInformation("Getting all the shared documents on site.");

                string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
                DocumentRequestModel docRequest = new DocumentRequestModel();

                _logger.LogInformation("Deserializing the request");
                docRequest = JsonConvert.DeserializeObject<DocumentRequestModel>(requestBody);

                try
                {
                    IFile doc = await pnpContext.Web
                       .GetFileByServerRelativeUrlAsync($"{pnpContext.Uri.PathAndQuery}/{docRequest.DocumentPath}");

                    Stream downloadedContentStream = await doc.GetContentAsync(true);

                    var bufferSize = 2 * 1024 * 1024;  // 2 MB buffer
                    using (var content = System.IO.File.Create("2gbdownloaded.zip"))
                    {
                        var buffer = new byte[bufferSize];
                        int read;
                        while ((read = await downloadedContentStream.ReadAsync(buffer, 0, buffer.Length)) != 0)
                        {
                            content.Write(buffer, 0, read);
                        }
                    }

                    return req.CreateResponse(HttpStatusCode.OK);
                }
                catch (Exception ex)
                {

                    throw ex.InnerException;
                }
            }
        }

## Environment details (*development & target environment*)

Azure function V4., .net 6, isolated process

PnP.Core.Admin" Version="1.8.60-nightly"
"PnP.Core.Auth" Version="1.8.60-nightly"

**Comment by jansenbe** [comment] 2023-01-09 08:38
Hi @lynath ,

When you test the Azure function locally (on your dev machine) or in a console application does it then also show this behavior? https://github.com/pnp/pnpcore/issues/1032 provides more context on a similar download question

**Comment by lynath** [comment] 2023-01-09 13:09
> Hi @lynath ,
> 
> When you test the Azure function locally (on your dev machine) or in a console application does it then also show this behavior? #1032 provides more context on a similar download question. Also give the non streaming approach a try and see if that one works (https://pnp.github.io/pnpcore/using-the-sdk/files-intro.html#downloading-files). In the end it's the same API call being made, only difference is that in the streaming one you'll get the file bytes chunk by chunk depending on the speed they come in. This approach prevents loading a large file in memory before returning it to the requestor.

@jansenbe I have this behavior when I am running it locally and also as a deployed azure function. I have also tried to use GetBytes method, but it is also showing the same behavior.

**Comment by lynath** [comment] 2023-01-10 18:26
@jansenbe any help on this?

**Comment by jansenbe** [comment] 2023-01-10 19:05
@lynath : I've just tested below code (from a unit test) and this worked as expected. A 64Mb video was downloaded and I could play the video afterwards so no bytes were missing. This code is similar to what you've shown, so not sure why it fails for you.

One thing to test is manually doing the same from the SharePoint UI: what happens under the covers is that we'll construct an URL like this one: https://contoso.sharepoint.com/sites/yoursite/_layouts/15/download.aspx?UniqueId=0a3094dd-7f0d-494b-8408-d224bb7de306 and then do a GET on that URL. You can see this URL when you use Fiddler or from the Visual Studio debug output or manually craft it. Once you've that URL verify that the download of the file works as expected by using it from your browser window where you've already loaded the site (so authentication was done). If that doesn't work then there's some issue with your tenant...

```csharp
IFolder parentFolder = await context.Web.Folders.Where(f => f.Name == "SiteAssets").FirstOrDefaultAsync();

// Get a reference to the file to download
IFile fileToDownload = await context.Web.GetFileByServerRelativeUrlAsync($"{parentFolder.ServerRelativeUrl}/donotdelete-sharingtest.mp4");

// Start the download
Stream downloadedContentStream = await fileToDownload.GetContentAsync(true);

// Download the file bytes in 2MB chunks and immediately write them to a file on disk 
// This approach avoids the file being fully loaded in the process memory
var bufferSize = 2 * 1024 * 1024;  // 2 MB buffer
using (var content = System.IO.File.Create("e:\\temp\\donotdelete-sharingtest.mp4"))
{
    var buffer = new byte[bufferSize];
    int read;
    while ((read = await downloadedContentStream.ReadAsync(buffer, 0, buffer.Length)) != 0)
    {
        content.Write(buffer, 0, read);
    }
}
```

**Comment by lynath** [comment] 2023-01-10 20:41
@jansenbe  I did go through the steps and it is generating a url like:
 https://contoso.sharepoint.com//_layouts/15/download.aspx?UniqueId=0a3094dd-7f0d-494b-8408-d224bb7de306.

The difference from your url is there is no path to the site and there is "//" in the url. when I use this url directly in the browser I am getting file not found error.

**Comment by jansenbe** [comment] 2023-01-10 20:48
Interesting find, that seems to be the root cause. I'll cross check tomorrow and fix if needed.

**Comment by jansenbe** [comment] 2023-01-10 21:50
@lynath : I just did a quick test downloading a file from the root site collection, this generates `https://bertonline.sharepoint.com//_layouts/15/download.aspx?UniqueId=77612ef1-a710-4645-b95d-e8d2ef40bb00` as url and the download succeeded. Also the URL works from the UI. What is the site url you're trying to download from?

**Comment by jansenbe** [comment] 2023-01-11 09:02
@lynath : you mentioned using the URL with double slashes in the browser fails, also if you remove the duplicate slash?

**Comment by lynath** [comment] 2023-01-11 15:13
@jansenbe It's failing even after I remove double slashes. it's a corporate SharePoint url which I cannot disclose.

**Comment by jansenbe** [comment] 2023-01-11 16:22
@lynath : Can you do a Fiddler trace and of the failing code and send that to bjansen@microsoft.com?

**Comment by jansenbe** [comment] 2023-01-13 09:03
@lynath : any update here?

**Comment by lynath** [comment] 2023-01-13 19:30
@Jansenbe I don't see any trace in the fiddler. Is there any option in Fiddler which I have to turn on for non/browser calls?
I did try to

**Comment by jansenbe** [comment] 2023-01-14 13:57
@lynath : you first of all need to configure Fiddler to decrypt HTTPS traffic: Tools -> Options and then configure like this.
![image](https://user-images.githubusercontent.com/7451219/212475416-288d70b7-055d-46a0-900c-4dc62dc812b1.png)

During this you'll be asked to install a certificate that Fiddler will use as proxy.

Second thing is launching Fiddler before you launch your program, that should get things working. 

Alternatively try getting more exception details. See [below code](https://pnp.github.io/pnpcore/using-the-sdk/basics-errorhandling.html#catching-a-pnp-core-sdk-exception-and-getting-the-exception-details): 

```csharp
try
{
    // Make service call    
}
// Catch all service exceptions
catch (ServiceException ex)
{
    // Option 1: Dump full error information to your log, including exception stacktrace
    Console.WriteLine(ex.ToString());

    // Option 2: Only handle SharePoint REST exceptions
    if (ex is SharePointRestServiceException)
    {
        // Let's get the detailed error information
        SharePointRestError error = ex.Error as SharePointRestError;

        // Write detailed error information to a log
        Console.WriteLine(error.ToString());
    }

    // Option 3: handle all service errors
    Console.WriteLine(ex.Error.ToString());
}
```

**Comment by lynath** [comment] 2023-01-16 12:26
@jansenbe The code is not going into the catch block. The call is successful but not returning more than 102kb.

**Comment by jansenbe** [comment] 2023-01-16 13:36
@lynath : weird, so there's no error then. When you try to open the downloaded file I assume it's corrupt?

**Comment by jansenbe** [comment] 2023-01-16 14:20
@lynath : do you have another tenant to test your code against? As I can't simulate the issue there's maybe something else blocking/corrupting the download. You can sign up for your own free development tenant via https://developer.microsoft.com/en-us/microsoft-365/dev-program in case you've no alternative tenant. Also, inspect the returned content : maybe there's an indication of an error in there?

**Comment by jansenbe** [comment] 2023-01-19 11:11
@lynath : checking in how things are going...

**Comment by jansenbe** [comment] 2023-01-23 19:00
@lynath : closing this one per no feedback. Feel free to re-open or send a trace directly to bjansen@microsoft.com

**Closed by jansenbe** 2023-01-23 19:00 UTC
Labels: question, area: framework ⚙
