### ISSUE TITLE
Unauthorized  exception when set site logo/thumbnail using app-only token

### ISSUE THREAD

**Issue by matsla** [pnp/pnpcore#1023] opened 2022-11-08 11:46 UTC
When set/reset site logo using an app-only token throws un unauthorized exception.

// This works fine with app-only token, have full control access to site collection
IField myField = await context.Web.Fields.AddTextAsync("My Test Field", new FieldTextOptions()
  {
    Group = "Test",
    AddToDefaultView = true,
    MaxLength = 30
  });

// All 3 logo methods throws 401 unauthorized exception using an app-only token
var chrome = await context.Web.GetBrandingManager().GetChromeOptionsAsync();
await chrome.Header.ResetSiteLogoAsync();
await chrome.Header.SetSiteLogoAsync(fileName, stream, true);
await chrome.Header.SetSiteLogoThumbnailAsync(fileName, stream, true);

Using PnP Version 1.7.112

**Comment by jansenbe** [comment] 2022-11-08 13:12
@matsla : I've done some testing with the branding features and app-only and also see the error whenever the image is set for a group connected site (e.g. a modern team site). For other sites (like a communication site) this works fine. The failing API call is this one: `_api/groupservice/setgroupimage`. This currently fails for both delegated and application permissions, so feels like some backend change caused this.

I'll do some more research.

**Comment by matsla** [comment] 2022-11-21 20:12
@jansenbe any updates?

**Comment by jansenbe** [comment] 2022-11-22 08:20
@matsla : not yet, I've not had the bandwidth to do a detailed investigation. Will be for after the ESPC conference (so week of December 5)

**Comment by matsla** [comment] 2022-12-13 16:06
@jansenbe any updates?

**Comment by jansenbe** [comment] 2022-12-14 11:47
@matsla : did some more research and the used API (`_api/groupservice/setgroupimage`) by design does not work when used via app-only permissions. Using delegated permissions the call succeeded in my testing. This aligns with your findings. I'll see what other options there are.

**Comment by matsla** [comment] 2022-12-14 12:40
@jansenbe this has been working with app-only permissions before reporting the issue.

**Comment by jansenbe** [comment] 2022-12-14 12:55
@matsla : I'm checking with feature crews, it might be that app-only now is blocked (at least that's what I see in my testing when I check logs). I've tried the Graph approach (PUT groups/{groupid}/photo/$value) but that's also not working via app-only :-(

At the moment I don't have a solution for this, will update this thread once I know more.

**Comment by matsla** [comment] 2022-12-14 13:49
@jansenbe have you tried using PATCH?

**Comment by jansenbe** [comment] 2022-12-14 14:05
@matsla : that returns the same error:

```json
{
    "error": {
        "code": "AppOnlyTokenNotSupportedForGroupUpdate",
        "message": "Exception of type 'Microsoft.Fast.Profile.Core.Exception.ProfileAccessDeniedException' was thrown.",
        "innerError": {
            "date": "2022-12-14T14:04:35",
            "request-id": "74246948-1445-46d2-9247-bb8842ee6337",
            "client-request-id": "74246948-1445-46d2-9247-bb8842ee6337"
        }
    }
}
```

**Comment by matsla** [comment] 2022-12-14 14:51
@jansenbe It supported to use application permission to update the group photo => https://learn.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&tabs=http

But it seems in the article that there is currently a [known issue](https://learn.microsoft.com/en-us/graph/known-issues#groups) with accessing group photos using application permissions.

**Comment by matsla** [comment] 2022-12-14 16:14
@jansenbe thanks for the reply, but we are not allowed to use a delegated model due to heavy platform restrictions ...

**Comment by jansenbe** [comment] 2023-01-20 18:50
@matsla : after more digging I unfortunately do not have a solution for you. It's best that you (if you're a customer) or one of your large customers (if you're an ISV) opens a support case with Microsoft and pushes this. Eventually you can request a DCR (Design Change Request) which will be evaluated by the respective feature crews.

What I've tried:
- POST _api/GroupService/SetGroupImage (works via delegated, fails via application permissions)
- POST groups/{id}/photo/$value (works via delegated, fails via application permissions)

I'll a note in the PnP Core SDK docs to explain this.

As there's nothing more I can do I'm going to close this issue, feel free to re-open or create a new one in case there are some new insights in this case. I'll do the same whenever I find a solution/workaround.

**Closed by jansenbe** 2023-01-20 18:50 UTC
Labels: bug, area: model 📐
