### ISSUE TITLE
Getting all items from a list returns only the first 100 items

### ISSUE THREAD

**Issue by plamber** [pnp/pnpcore#604] opened 2021-10-30 05:42 UTC
## Category

- [x] Bug

## Describe the bug

I was looking for a way to retrieve all list items from a SharePoint Online list with more than 100 items. I was looking at your [sample](https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#getting-all-list-items) code showing how to retrieve all items from a list. Apparently, only the first 100 items are returned by default.

## Expected behavior

Either this is a bug or the documentation should be updated.

## Environment details (*development & target environment*)

SharePoint Online environment with a list with more than 100 items

- **SDK version**: 1.4
- **OS**:  Windows 10
- **SDK used in**:  .NET Core 3.1

**Comment by jansenbe** [comment] 2021-10-30 08:16
Hi @plamber ,

Thanks for reporting this. This is a known issue that should be fixed in our current nightly builds. Can you try with the latest nightly and verify if you still have this issue?

**Comment by plamber** [comment] 2021-10-30 09:17
Hi @jansenbe,
I updated to the latest nightly version:
![image](https://user-images.githubusercontent.com/18241305/139527293-ae0cd83a-cde7-4ba4-bbc7-15f8ef08b82f.png)

I am still having the same issue. It just returns the first 100 items. Not sure if this matters but I am running the query on a list with around 1000 items.

I can retrieve all 1000 items by performing such a query
```
string viewXml = @"<View>
                    <ViewFields>
                      <FieldRef Name='Title' />
                    </ViewFields>
                    <RowLimit>2000</RowLimit>
                   </View>";

await projects.LoadItemsByCamlQueryAsync(new CamlQueryOptions()
{
    ViewXml = viewXml,
    DatesInUtc = true
});
```

Cheers

**Comment by jansenbe** [comment] 2021-10-30 09:30
Thanks for reporting this @plamber . Would it be possible to share how you load the items, there's various options so want to be sure I'm testing your approach.

**Comment by plamber** [comment] 2021-10-30 09:45
Hi @jansenbe,
this code does not work

```
var projects = projectList.GetByTitle("Projects", p => p.Title, p => p.Items,
                                                     p => p.Fields.QueryProperties(p => p.InternalName,
                                                                                   p => p.FieldTypeKind,
                                                                                   p => p.TypeAsString,
                                                                                   p => p.Title));
                       
var items = projects.Items.AsRequested().Where(p => String.Equals(p.Title, "MyTitle", StringComparison.InvariantCultureIgnoreCase));
```

At first glance it looks almost the same as the sample code. Maybe I am missing something.

Thank you,
Patrick

**Comment by jansenbe** [comment] 2021-10-30 10:00
Thanks for the details @plamber , in above sample there's should be no paging at all, just an expand on listitems. I'll cross check and report back

**Comment by jansenbe** [comment] 2021-10-31 09:45
@plamber : I can reproduce what you see, SharePoint is only returning the first 100 list items when loading them via REST (only for ListItems, expanding 100+ fields works fine). This is by design (see https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest?redirectedfrom=MSDN#retrieve-all-list-items) to safeguard the infrastructure from code getting all list items on a 1 million item library...so kind of makes sense. I'll update this in documentation as I forgot about it as well (as I usually use CAML based approaches).

Best is that you use an async iterator on the items, this will automatically page them in the background:

```csharp
var projects = context.Web.Lists.GetByTitle("Large", p => p.Title, /* p => p.Items */
                                                 p => p.Fields.QueryProperties(p => p.InternalName,
                                                        p => p.FieldTypeKind,
                                                        p => p.TypeAsString,
                                                        p => p.Title));

//var items = projects.Items.AsRequested().Where(p => String.Equals(p.Title, "MyTitle", StringComparison.InvariantCultureIgnoreCase));

int count = 0;
await foreach(var item in projects.Items)
{
    count++;
}
```

**Comment by plamber** [comment] 2021-10-31 10:33
Awesome. Thank you

The updated documentation will definitely help

**Comment by jansenbe** [comment] 2021-11-02 15:39
@plamber : see updated docs: https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#reading-list-items. I've clearly defined 4 approaches to read list items and a model to chose the best method for the job.

**Closed by jansenbe** 2021-11-02 15:39 UTC
Labels: question, area: framework ⚙
