### ISSUE TITLE
GetFolderByServerRelativeUrlAsync not working anymore with path from System.IO.Path [regression?]

### ISSUE THREAD

**Issue by FlorianLabranche** [pnp/pnpcore#1412] opened 2024-03-05 14:34 UTC
## Category

- [x] Bug

## Describe the bug

Retrieving folder from path handled using System.IO.Path was working fine in PnP.Core 1.10
When upgrading SDK to 1.12, the same code returns a 404 'File Not Found.' exception.

## Steps to reproduce

Below code snippet returns an exception in SDK 1.11 and 1.12 but works fine in 1.10
```
var directoryPath = Path.GetDirectoryName(file.ServerRelativeUrl);
var folder = await PnPContext.Web.GetFolderByServerRelativeUrlAsync(directoryPath);
```

_This snippet is only to demonstrate the issue. In this case, to retrieve the folder, I would use `file.ListItemAllFields.GetParentFolderAsync()`._

## Expected behavior

I don't know if this should be handled by the library because the issue is related to the path being encoded by System.IO.Path.
Backslashes are escaped.
![image](https://github.com/pnp/pnpcore/assets/23434632/01264ece-2967-4e12-b525-8d735782ac42)

But as this was working in a previous release, I raise it as a bug.

## Environment details (*development & target environment*)

- **SDK version**: 1.12
- **OS**: Windows 10
- **SDK used in**: ASP.Net Web app
- **Framework**: .Net 6
- **Tooling**: Visual Studio 2022

### Additional context

Code is working once deployed in a Linux Web App.
But path are handled differently in linux.

**Comment by jansenbe** [comment] 2024-03-05 15:18
@FlorianLabranche : assume there's no difference in casing between testing with 1.11 and 1.12?

**Comment by FlorianLabranche** [comment] 2024-03-05 16:33
No difference.
1.10 :    "\\sites\\DMS_prj_90480\\Correspondence" (working)
1.11/1.12 :  "\\sites\\DMS_prj_90480\\Correspondence" (not working)

**Comment by jansenbe** [comment] 2024-03-06 06:42
@FlorianLabranche : can you do a Fiddler trace and compare both GET requests, spotting the difference there will help identify the root cause. Also, does it fail on Linux, on Windows or both?

**Comment by jansenbe** [comment] 2024-03-08 09:05
@FlorianLabranche : looking at the code this is the most recent change here, would not expect this to result in what you see...

![image](https://github.com/pnp/pnpcore/assets/7451219/e4958b6c-df32-4458-b277-37198b364c09)

**Comment by jansenbe** [comment] 2024-03-08 09:06
@FlorianLabranche : does it also happen with sites that do not have an _ in their name?

**Comment by jansenbe** [comment] 2024-03-13 09:40
@FlorianLabranche : any updates here?

**Comment by FlorianLabranche** [comment] 2024-03-13 16:20
@jansenbe here are the results of my tests :

- 1.10 

`/sites/DMS_prj_90480/_api/Web/getFolderByServerRelativePath(decodedUrl='%5Csites%5CDMS_prj_90480%5CCorrespondence')`
- 1.11 or 1.12

`/sites/DMS_prj_90480/_api/Web/getFolderByServerRelativePath(decodedUrl=@u)?@u='%5Csites%5CDMS_prj_90480%5CCorrespondence'`

The encoded path is the same, so '\\' is not an issue.
In the second case, if I replace '\\\\' by '/' before I make the call, it works with the following URL:
`/sites/DMS_prj_90480/_api/Web/getFolderByServerRelativePath(decodedUrl=@u)?@u='%2Fsites%2FDMS_prj_90480%2FCorrespondence'`

Targeting sites with or without _ in their url has no impact.

Issue seems to come from the change you shared.

**Comment by jansenbe** [comment] 2024-03-13 17:29
@FlorianLabranche : interesting, tested this and so it seems that using the "parameter" model requires the server relative path to use / while the previous one worked with either / and \. I'll update the code to handle that automatically

**Comment by FlorianLabranche** [comment] 2024-03-13 17:42
It's weird they behave differently, indeed.
Many thanks

**Comment by jansenbe** [comment] 2024-03-13 17:48
@FlorianLabranche : pushed an update, thanks for raising this one :-)

Closing issue now, please re-open if things don't seem to work

**Closed by jansenbe** 2024-03-13 17:48 UTC
Labels: question
