### ISSUE TITLE
Implement ASPXPageIndexMode

### ISSUE THREAD

**Issue by iloving** [pnp/pnpcore#494] opened 2021-06-22 18:48 UTC
## Category

- [x] Feature request

## Describe the feature

PnP is currently not able to configure the Site setting "ASPXPageIndexMode", which corresponds to Site Settings->Search and Offline Availability->Indexing ASPX Page Content.  

A ticket was opened on the old SDK but that appears to be abandoned. https://github.com/pnp/PnP-Sites-Core/issues/2520

## Describe the solution you'd like

We need to be able to configure this setting as part of our site creation automation.  Currently our sites are not getting indexed without having to manually update the setting.  We would like to be able to configure this setting as part of the powershell/pnpframework script that is creating the site.

**Comment by jansenbe** [comment] 2021-06-23 16:54
@iloving : the property is available in REST (https://s-kainet.github.io/sp-rest-explorer/#/entity/SP.Web) and already implemented as a get in the SDK. I'll enable this to be also set, would that then unblock you?

**Comment by iloving** [comment] 2021-06-24 14:59
It would.  While I have only identified needing this specific setting editable, would it be a big deal to do the same with any others?  I'm sure I'm not the only one that wants to use PnP to handle all the site deployment automation.

**Comment by jansenbe** [comment] 2021-06-24 15:58
The property now is settable in the SDK. Which other properties do you need to get added?

**Comment by iloving** [comment] 2021-06-24 16:02
At this point I don't know because I've been blocked by this.  I'm just saying that, unless there is a reason for a property to not have a set method, properties should have both get/set by default instead of waiting for people to make an explicit request.

**Comment by iloving** [comment] 2021-06-24 16:37
I'm still not seeing the property with the the latest Pnp.Powershell nightly.  Is there something else I need to do?

**Comment by jansenbe** [comment] 2021-06-24 17:32
The property was added in PnP Core SDK...not all PS cmdlets use PnP Core SDK. Think you need an additional argument in `Set-PnPWeb` that can set this property. If so please create an issue in the PowerShell repo to request this.

Alternatively you can use the PS CSOM returned object, something like this work:

```PowerShell
$web = Get-PnPWeb -Includes AllowAutomaticASPXPageIndexing
$web.AllowAutomaticASPXPageIndexing = $true
Invoke-PnPQuery
```

**Comment by iloving** [comment] 2021-06-24 19:00
Just to confirm, I hope you mean ASPXPageIndexMode because AllowAutomaticASPXPageIndexing is already there.

**Comment by DaleyKD** [comment] 2021-06-24 19:45
@iloving - I see zero indication that `ASPXPageIndexMode` is a property available to us via SharePoint REST or SharePoint CSOM.  It appears to only be available via SharePoint SSOM (server-side object model).

I don't know how `AllowAutomaticASPXPageIndexing` and `ASPXPageIndexMode` correlate if at all.

**Comment by jansenbe** [comment] 2021-06-25 07:30
@iloving : ASPXPageIndexMode is not exposed to client side APIs (neither REST, CSOM or Graph) and therefore there's no option to configure this value for SPO. This is by design and this project can't change the SharePoint APIs, hence closing this issue. If you really feel this is a blocker for you then please work with our support organization to voice this concern.

**Closed by jansenbe** 2021-06-25 07:30 UTC
Labels: area: model 📐, question
