### ISSUE TITLE
Time Conversion LocalToUTC and UTCtoLocal

### ISSUE THREAD

**Issue by gopaldahal** [pnp/pnpcore#484] opened 2021-06-14 03:33 UTC
## Category

- [x] Feature request

## Describe the feature

Date conversion from LocalToUTC and UTCtoLocal is available on Rest and CSOM.
-UTC to Local Time
-Local To UTC time

**Rest Reference**
https://s-kainet.github.io/sp-rest-explorer/#/entity/SP.TimeZone

**Equivalent Code on CSOM**
var conversionType = DateTimeKind.Utc or DateTimeKind.Local;
var specifiedDate= DateTime.SpecifyKind(dtVal, conversionType );
Microsoft.SharePoint.Client.Utilities.Utility.FormatDateTime(context, context.Web, specifiedDate, Microsoft.SharePoint.Client.Utilities.DateTimeFormat.ISO8601);

## Describe the solution you'd like

Searching for equivalent methods.

## Additional context

Sharing is Caring!

**Comment by DaleyKD** [comment] 2021-06-16 19:34
Maybe I'm way off base here, but I would have thought the purpose of the SharePoint REST functions would be to convert times based on the **WEB'S** time zone.

Doing a local implementation like this is going to be based on the local server's time zone.  If I'm calling `context.Web.RegionalSettings.TimeZone.UtcToLocalTime`, and that is set as Pacific, I'd expect that to come back as Pacific, even though my local server is Central.

Mind you, this is purely based on looking at the commit.

**Comment by gopaldahal** [comment] 2021-06-17 03:21
I agreed with @DaleyKD statements. The conversion is supposed to be based on **Webs** time zone.
If it's the same it's perfect @jansenbe, else may need some additional improvements.
Thank you.

**Comment by jansenbe** [comment] 2021-06-17 07:45
@DaleyKD , @gopaldahal : below is the used code. The reasoning I followed is this:

- context.Web.RegionalSettings.TimeZone is always loaded with the timezone of the web
- The TimeZone entity contains information about how this timezone differs from UTC, expressed via the Bias properties
- The code calculates the difference between the UTC and the web's timezone and uses that to change the date 

In my testing I used this (in both directions) and I think this is the expected behavior, but feel free to tell me otherwise. 

@gopaldahal: please give the current implementation a try and compare with the results you got from calling the server.

Local time (UTC + 1, daylight savings) | UTC | Web time (PCT, UTC -8, daylight savings)
------------------------------------------|------|---------------------------------------------
 15:15 | 13:15 | 06:15


Actual test code for above table:

```csharp
// Datetime in timezone of the code running PnP Core SDK
var localDate = new DateTime(2021, 7, 15, 15, 15, 15);

// Convert to UTC time
var utcDate = localDate.ToUniversalTime();

// Convert to Web's timezone
var localSiteTime = context.Web.RegionalSettings.TimeZone.UtcToLocalTime(utcDate);

// Convert from Web's timezone back to UTC time
var localSiteTimeBackToUtc = context.Web.RegionalSettings.TimeZone.LocalTimeToUtc(localSiteTime);

Assert.AreEqual(utcDate, localSiteTimeBackToUtc);

// Convert back to timezone of the running code
var utcDateBackToLocal = localSiteTimeBackToUtc.ToLocalTime();

Assert.AreEqual(localDate, utcDateBackToLocal);
```

Actual implementation:

```csharp
public DateTime LocalTimeToUtc(DateTime dateTime)
{
    return dateTime + UtcDelta(dateTime);
}

public DateTime UtcToLocalTime(DateTime dateTime)
{
    return dateTime - UtcDelta(dateTime);
}

private TimeSpan UtcDelta(DateTime dateTime)
{
    return new TimeSpan(0, Bias + (TimeZoneInfo.Local.IsDaylightSavingTime(dateTime) ? DaylightBias : StandardBias), 0);
}
```

**Comment by DaleyKD** [comment] 2021-06-17 13:39
@jansenbe : The ONLY thing that threw me off was seeing `TimeZoneInfo.Local`.  Everything else to that point made sense.

Now I see some commits from today adding NuGets to try and be platform independent because of Linux/macOS and how they do TimeZoneInfo differently.

I politely ask: is it worth it for this one edge-case, instead of just calling SharePoint REST?

I'll also throw out the SUPER edge-case question: the potential that the NuGet package differs from SharePoint Online regarding the most up-to-date Time Zone info revolving around Daylight Saving time (I remember when US Congress passed the law changing when it happen and SharePoint on-prem .xml wasn't updated for quite a while. :smile: )

I apologize if this seems like I'm splitting hairs.  I know as developers we have ALL fought this "time" fight before.

**Comment by jansenbe** [comment] 2021-06-17 14:17
@DaleyKD : you're right about the ".Local"...I realized that as well...so just pushed a commit that translates a SharePoint timezone into a .NET TimeZoneInfo, so I can use the "web" timezone to assess whether DST is in play or not. It took more time than planned, but it bothered me that a server roundtrip was needed for this, especially since when working with items you might need to "convert" a lot of dates. If really needed we can still wrap the REST call in the SDK (like done in the tests), but would like to get an "offline" system working

**Comment by gopaldahal** [comment] 2021-06-18 04:09
@jansenbe, Thank you for the update. However, I need some time for its verification.
I strongly agree with the "Server call on lots of Dates". I assume this is strongly required, as there could be lots of dates on the same item. So it would be great if we have these functionalities within our PnP.Core.

**Comment by jansenbe** [comment] 2021-06-18 06:07
@gopaldahal , thanks for the feedback. I'm closing this issue now, best to open a new issue if you have problems with the implemented UtcToLocalTime and LocalTimeToUtc methods.

**Closed by jansenbe** 2021-06-18 06:07 UTC
Labels: area: model 📐
