### ISSUE TITLE
GetAvailableThemesAsync throws exception when 'isInverted' or 'name' values missing from JSON response

### ISSUE THREAD

**Issue by kgr-kpmg** [pnp/pnpcore#990] opened 2022-10-10 16:53 UTC
## Category

- [x] Bug

## Describe the bug
Not entirely sure if this is an issue with the theme that was uploaded or with SharePoint or with the SDKs handling of the theme, but presumably SharePoint is treating it as valid.

`context.Web.GetBrandingManager().GetAvailableThemesAsync()` throws KeyNotFoundException when theme JSON is missing `name` or `isInverted` properties.

## Steps to reproduce

1. Upload theme without `isInverted` or `name` properties
2. Try to fetch themes from site using `await context.Web.GetBrandingManager().GetAvailableThemesAsync();`

## Expected behavior
Error is handled and default values provided.

## Environment details (*development & target environment*)

- **SDK version**: 1.7.0
- **OS**: Windows 10
- **SDK used in**: Azure function
- **Framework**: .NET 6
- **Browser(s)**: n/a
- **Tooling**: n/a
- **Additional details**: See below

### Additional context
PnP.Core.Model.SharePoint.BrandingManager.NormalizeThemeJson(String themeJson)

    var body = new
    {
        backgroundImageUri = "",
        palette = paletteValues,
        cacheToken = "",
        isDefault = true,
        isInverted = customThemeJson.GetProperty("isInverted").GetBoolean(),
        version = ""
    };

    var final = new
    {
        name = customThemeJson.GetProperty("name").GetString(),
        themeJson = JsonSerializer.Serialize(body),
    };

Other code in this same method uses TryGetProperty as opposed to GetProperty which causes an exception.

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment] 2022-10-11 08:36
@kgr-kpmg : makes indeed sense to add additional validation on those two properties.

**Comment by jansenbe** [comment] 2022-10-11 08:39
@kgr-kpmg : a change has been pushed, please test using next nightly release (version 1.7.97 or higher). I'm already closing the issue, but feel free to re-open in case the problem is still not solved for you. 

Thanks for using PnP Core SDK and providing feedback!

**Closed by jansenbe** 2022-10-11 08:39 UTC
Labels: bug, area: model 📐
