### ISSUE TITLE
GetComments() only return maximum of 30 comments. It used to return all comments.

### ISSUE THREAD

**Issue by larry-lau** [pnp/pnpcore#1361] opened 2024-01-29 18:06 UTC
## Category

- [x] Bug

## Describe the bug

GetComments() used to return all comments. Now it is only returning 30 comments.  

## Steps to reproduce

1. See code block below
1. Add the following unit test  to the PagesTests.cs in PnP.Core.Test project
1. Run the test without mocking turned off.
1. Assertion failure since it returns 30 comments instead of 45 that get added in this test. 

```
[TestMethod]
public async Task PageCommentingTestOnlyReturn30Comments()
{
    TestCommon.Instance.Mocking = false;
    using (var context = await TestCommon.Instance.GetContextAsync(TestCommon.TestSite))
    {
        var newPage = await context.Web.NewPageAsync();
        string pageName = TestCommon.GetPnPSdkTestAssetName("PageCommentingTest.aspx");

        // Save the page
        await newPage.SaveAsync(pageName);

        // Publish the page, required before it can be liked
        newPage.Publish();

        // Get Page comments                
        var comments = newPage.GetComments();
        Assert.IsTrue(comments.Length == 0);

        var noCommentsAdded = 45;

        foreach (var i in Enumerable.Range(1, noCommentsAdded))
        {
            // Add a comment
            comments.Add($"Comment #: {i} added by unit test");
        }

        comments = newPage.GetComments();
        // Expecting 45 but only 30 is returned. 
        Assert.IsTrue(comments.Length == noCommentsAdded);

        // Delete the page
        await newPage.DeleteAsync();
    }
}
```

## Expected behavior

GetComments() should return all comments like it used to. 

## Environment details (*development & target environment*)

- **SDK version**: 1.11.0
- **OS**: [e.g. Windows 10 | MacOS 10.15.x]
- **SDK used in**: [Console App]
- **Framework**: [.NET 7/8 ]
- **Browser(s)**: [N/A]
- **Tooling**: [Visual Studio 2021]
- **Additional details**: **

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment] 2024-01-30 08:36
@larry-lau : from when did this we limit the amount of comments to 30?

**Comment by larry-lau** [comment] 2024-01-30 16:24
> @larry-lau : from when did this we limit the amount of comments to 30?

@jansenbe I am not 100% sure.  I am looking at the pnpcore code and it is just making HTTP GET on the SharePoint REST API _api/web/lists(guid'{List.Id}')/getitembyid({Id})/getcomments and I didn't see any limit imposed there.  I am curious if it should have pagination logic to fetch all comments.

**Comment by jansenbe** [comment] 2024-01-30 17:23
@larry-lau : or some server side change. Can you capture the REST query and see if it returns all items when you invoke it directly?

**Comment by larry-lau** [comment] 2024-01-31 19:43
@jansenbe: The response doesn't returns all items but it does return odata.nextLink what we could use to fetch more data https://xxx.sharepoint.com/sites/TestNews1Edited/_api/web/lists(guid%27aec597d6-13ea-4f08-9b41-a03c19200281%27)/getitembyid(8)/getcomments?%24skiptoken=AAAAABAAAAAAAAAA8FapEvIg3Eg1

I am curious if pnpcore support following the odata.nextLink to fetch all comments.

**Comment by jansenbe** [comment] 2024-02-15 18:12
@larry-lau : I've reprod this at my side as well (thanks for sharing the test case!). Will see if I can get this one fixed.

**Comment by jansenbe** [comment] 2024-02-15 19:07
@larry-lau : and the issue is fixed, fix will be next nightly, so closing this now.

Seems as the API implementation changed and now uses paging by 30 items

**Closed by jansenbe** 2024-02-15 19:07 UTC
Labels: bug, area: model 📐
