### ISSUE TITLE
Exception messages get truncated with Azure Functions / App Insights

### ISSUE THREAD

**Issue by JakeStanger** [pnp/pnpcore#1314] opened 2023-11-02 13:29 UTC
## Category

- [x] Bug

## Describe the bug

When PnP Core throws an exception inside Azure Functions (ie captured from a request), all the server response part of the message is lost inside the Application Insights logging.

For example, a failed SPO Rest request throws a `SharePointRestServiceException`. The message in Application Insights shows as just "SharePoint Rest service exception". No other lines of the exception message are present.

This makes it very hard to debug some issues.

## Steps to reproduce

1. Set up PnP Core inside Azure Functions, with Application Insights configured.
2. Send an invalid request inside the app.
3. View the Application Insights log for the exception:
```kql
exceptions | where operation_Id == "<id>"
```
4. Observe the `innermostMessage` and `details.message` values missing the exception details.

## Expected behavior

The full exception details should be visible in Application Insights, either as part of the message or otherwise.

## Environment details (*development & target environment*)

- **SDK version**: 1.10.0
- **OS**: Windows
- **SDK used in**: Azure Functions v4 (.NET 6 in-process)
- **Framework**: .NET 6

### Additional context

My assumption is that this is because the message is formatted across multiple lines and App Insights cuts all but the first line off. If that is the case, changing the exception formatting feels a bit heavy-handed. 

Arguably this could be viewed as a bug with Application Insights incorrectly truncating values.

It is possible to get some data out as a workaround using `dependencies | where operation_Id  == "<id>"` instead since Application Insights captures all outgoing requests. This allows you to find the request that failed and the response code, but no response body.

**Comment by Gareth064** [comment] 2023-12-08 12:02
Can you share a screenshot of the issue with truncated messages?

When we get `SharePointRestServiceException` exceptions, the full error appears in App Insights fine.

![image](https://github.com/pnp/pnpcore/assets/22307223/0c828197-31fc-43a1-b5ea-b7ac65278904)

**Comment by JakeStanger** [comment] 2023-12-11 12:42
Interesting. Are you doing anything out of the ordinary to capture logs into AI? In my case I have not touched any of the Azure Functions settings except to disable sampling, and let it do all the work capturing exceptions.

Here's what I get from a KQL query:

![image psd](https://github.com/pnp/pnpcore/assets/5057870/34ddd367-9844-4a8c-80e6-033985de4279)

I also went through the transaction log as you did just in case, and I noticed my `PnP.Core.SharePointRestException` entries are missing the `FormattedMessage` key (it's present on other types). From what you've shown, it sounds like the fact I have that key missing is the issue here - any ideas on how to get that or why it'd be missing?

**Comment by jansenbe** [comment] 2024-01-10 17:41
@JakeStanger : did you ever find a solution here? Not sure if this actually is a PnP Core SDK issue? If not, are you good with closing this one?

**Comment by JakeStanger** [comment] 2024-01-10 17:45
I've not managed to get anywhere and have no workaround except "run locally with debugger" which is less than ideal, so would prefer to keep it open please - I weirdly came back to this thread to see if I'd missed anything about 30 minutes ago as I ran into this again. 

It may be that this is not a bug with PnP Core (it could be a configuration issue?, but I do know that with the default Azure Functions & App Insights configurations, this consistently occurs for me across applications and environments, whereas other libraries do not suffer the same issue.

**Comment by jansenbe** [comment] 2024-01-10 18:07
Maybe @Gareth064 has more details on possible specific in his setup?

**Comment by Gareth064** [comment] 2024-01-10 18:46
I will share my setup tomorrow when I get back to work 👍

**Comment by Gareth064** [comment] 2024-01-11 10:03
Ok. I have encapsulate my pnpCore code in my own library then using my library in my app, so bare with me if this ends up a bit over the place.

Lets start with the library where I have pnpCore setup.

This is inside my ServiceCollection extension method

```cs
        services.AddPnPCore(options =>
        {
            var authProvider = new X509CertificateAuthenticationProvider(clientId,
                tenantId,
                StoreName.My,
                StoreLocation.LocalMachine,
                certificateThumbprint);

            options.DefaultAuthenticationProvider = authProvider;

            foreach (var site in sites)
            {
                var siteUrl = $"{baseSiteURL}/sites/{site}";

                options.Sites.Add(site,
                    new PnP.Core.Services.Builder.Configuration.PnPCoreSiteOptions
                    {
                        SiteUrl = siteUrl,
                        AuthenticationProvider = authProvider
                    });
            }

            options.PnPContext.GraphFirst = false;
        });

        services.AddLogging();
```

So as far as I can tell I have put the AddLogging() there at the end which comes from `Microsoft.Extensions.DependencyInjection`

Now when I am writing code and want to catch and log exceptions I do this

Inject the default dotnet logger

```cs
    private readonly IPnPContextFactory contextFactory;
    private readonly ILogger<SPOFilingService> logger;

    public SPOFilingService(IPnPContextFactory pnpContextFactory, ILogger<SPOFilingService> logger)
    {
        contextFactory = pnpContextFactory;
        this.logger = logger;
    }
```
try catch the  `ServiceException` which comes from pnpCore/SharePoint

```cs
        try
        {
            document = await pnpContext.Web.GetFileByServerRelativeUrlAsync(path,
                f => f.ListItemAllFields.QueryProperties(li => li.All));
        }
        catch (ServiceException ex)
        {
            string serviceRrrorMessageToLog = ParseServiceExceptionForMessage(ex);
            string messageToLog = $">>> Error retrieving document {documentUrl} in site {site}.\n{serviceRrrorMessageToLog}";
            logger.LogError(ex, messageToLog);

            throw new ApplicationException(messageToLog, ex);
        }
```

I then parse it to get the actual message using `ParseServiceExceptionForMessage(ex)`

```cs
    private static string ParseServiceExceptionForMessage(ServiceException ex)
    {
        string errorMessageToLog = ex.ToString();

        if (ex is SharePointRestServiceException)
        {
            SharePointRestError? error = ex.Error as SharePointRestError;
            string spoErrorMessage = error!.ToString();
            errorMessageToLog = String.Concat(errorMessageToLog, $"\nError String: {spoErrorMessage}", $"\nError Message: {error.Message}");
        }

        return errorMessageToLog;
    }
```

Then I just use the built in logger to log the whole exception to App insights

```cs
logger.LogError(ex, messageToLog);
```

This results in the exception logged in App insights that I shared above

![image](https://github.com/pnp/pnpcore/assets/22307223/23fca23a-7611-473a-ae53-ff1a8ecc5eee)

Next, inside the Program.cs of my actual WebService, where I use my library, the only notable thing related to logging with app insights is this

```cs
builder.Services.AddApplicationInsightsTelemetry(options =>
{
    options.EnableAdaptiveSampling = false;
});
```

**Comment by JakeStanger** [comment] 2024-01-11 17:42
Really appreciate you taking the time to detail that, thank you. I think I can spot the important difference here, which is that you are explicitly logging the errors (ie you are catching the exception, and calling `logger.LogError`). In my case, the exceptions are uncaught and get automatically logged. 

Based on that, I'd say:

- It looks like this is an issue with how Application Insights plays with PnP Core. It could be something as simple as the fact that PnP Core uses multi-line exception messages and Application Insights only takes the first line.
- No idea what the fix for that would be if that is the case?
- If no fix can be realistically implemented, the docs should be updated to detail this, as this means you cannot rely on the implicit uncaught exception logging.

**Comment by jansenbe** [comment] 2024-01-12 08:29
@JakeStanger : I assume AppInsights eventually will call `ToString` on the Exception instance, which will call this code: https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core/Exceptions/SharePointRestServiceException.cs#L43-L46. As you can see we're using `Environment.NewLine` to create a multiline string. 

Idea: maybe this is caused by your code calling this on a Linux platform resulting in a string that uses `\n` while AppInsights expects a `\r\n`?

**Comment by JakeStanger** [comment] 2024-01-12 11:15
> Idea: maybe this is caused by your code calling this on a Linux platform

Unfortunately not, as I have only tested this on Windows. It might be worth giving Linux a short go to see if I do hit the problem there still though.

Once I get some time, I'll investigate this a bit further and see if I can track down exactly what App Insights is grabbing from the exception and how.

**Comment by jansenbe** [comment] 2024-02-15 17:46
@JakeStanger : did you manage to further investigate? If this is not an issue in PnP Core SDK then let's close it

**Comment by JakeStanger** [comment] 2024-02-16 20:21
This completely fell off my radar, sorry. I've not had time at all yet. If you want to close for now, I'll try and investigate when I can & will re-open if it does look like a PnP Core issue?

**Closed** 2024-02-17 08:49 UTC
Labels: question
