### ISSUE TITLE
File.TimeLastModified Incorrect?

### ISSUE THREAD

**Issue by duanepfeiffer** [pnp/pnpcore#959] opened 2022-08-31 14:36 UTC
I recently copied thousands of folders and files to sharepoint.  Some but not all of the files have a different TimeLastModified than what is shown when I view the same files on sharepoint.com with a browser.  Why?  Is there a way to get the last modified time that is showing in the browser?

Thanks

**Comment by jansenbe** [comment] 2022-08-31 16:30
Interesting finding @duanepfeiffer. From the PnP Core side we're just getting the properties from SharePoint, not sure why there would be a difference. What could maybe explain this is the difference between the last modified data of the list item in the library (what you're seeing) and the actual change of the file linked to that list item. Are you sure that the file in question was actually changed on the date you're seeing in the browser?

**Comment by duanepfeiffer** [comment] 2022-08-31 16:37
The date in the browser is the correct date.  I've discovered a similar issue after renaming a parent folder.  All subfolders and files in the browser retain the original modified date, but using the sdk I get the date the parent folder was renamed.

**Comment by jansenbe** [comment] 2022-08-31 18:17
I guess this is by design, one can argue whether that's correct or not...but it's not something we can control via PnP Core SDK, therefore I propose to close this issue. Ok for you @duanepfeiffer ?

If you want to see this behavior changed the next step would be creating a support case for it.

**Comment by duanepfeiffer** [comment] 2022-08-31 18:26
In my opinion, the real last modified date is what is showing in the browser and NOT what is coming from the sdk.   Clearly there are two different dates.   So maybe there should be two last modified times available from the sdk?  (FileLastModifiedTime and ListLastModifiedTime).  I would like to have both!  Is there some way to do that?

**Comment by jansenbe** [comment] 2022-09-01 14:38
@duanepfeiffer : if you want the time as displayed in the list you should retrieve the needed list items: see https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#reading-list-items on how to do that. When we return `IFile.TimeLastModified` then we just return what we get from SharePoint when loading a file. Don't see how we should update PnP Core SDK for this, hence the suggestion to close the issue.

**Comment by jansenbe** [comment] 2022-09-05 14:45
@duanepfeiffer : I'm going to close this issue as it's not SDK related. Getting the date time via querying the respective list items instead of the files should show the correct values. Happy to discuss more, but let's then open a discussion instead of an issue.

**Closed by jansenbe** 2022-09-05 14:45 UTC
Labels: question
