### ISSUE TITLE
Failure setting values of multi choice fields in libraries

### ISSUE THREAD

**Issue by mfxits** [pnp/pnpcore#1396] opened 2024-02-17 12:01 UTC
## Category

- [x] Bug

## Describe the bug

There is an inexplicable limit for entries in multi choice fields (MCF) when setting them with `IListItem.UpdateAsync()` in a library.
This makes it impossible to write a larger number of entries to a MCF. 

If the limit is hit, all updates to _all_ list item fields are silently dropped. Even the content type won't be set. _No exception is thrown_.

Tests have shown: 

- The limit is varying. In tests with different libraries and different numbers of MCF in the content type, it was between 13 and 17 entries (choices).
- This does not affect lists, **only libraries**.
- I doesn't matter if the file is tagged directly after uploading with `Files.AddAsync()` or later after a `GetFileByXY()`
- Uploading or tagging the same files to/in the same library with pnp/powershell instead of pnp/core works.
- When using pnp/powershell or tagging a list, it is possible to set _at least 10k entries_ with a length of 12-15 characters each (more than 100k bytes) in one or more MCF.

**EDIT**:
`UpdateOverwriteVersion()` doesn't have this bug and can be used as workaround.
([Thanks to](#issuecomment-1950284949) @jansenbe)

## Steps to reproduce

```
            // prepare the MCF test data 

            var mcf = new List<string>();

            for (var i=0; i<100; i++) {
                mcf.Add(i + "-0123456789");
            }

            var metaData = new Dictionary<string, object>
            {
                ["MCF1"] = mcf,
                ["MCF2"] = mcf,
                ["ContentTypeId"] = "0x010090A7731B1F4E5D498FB940A6316D9C0F"
            };

            // upload the file and tag it 

            IFolder targetFolder = await targetCtx.Web
               .GetFolderByServerRelativeUrlAsync($"{targetCtx.Uri.PathAndQuery}/MCFTestLib");

            try
            {
                using FileStream inStream = System.IO.File.OpenRead(uploadFilePath);

                IFile addedFile = await targetFolder.Files.AddAsync(targetFileName,
                                  inStream, overwrite: true);

                var lItem = addedFile.ListItemAllFields;
                await lItem.LoadAsync();

                foreach (var field in metaData)
                {
                    lItem[field.Key] = field.Value;
                }
                await lItem.UpdateAsync();
            }
            catch (Exception) { 
                // never hit
            }

```
![2024-02-17 PnP Core Library MultiChoice Updates Bug](https://github.com/pnp/pnpcore/assets/120029769/a83c0709-d0cf-4d2e-8f84-9df45eb9ca65)

## Expected behavior

The same as with lists or pnp/powershell.

## Environment details (*development & target environment*)

- **SDK version**: 1.11.68-nightly
- **OS**: Windows 10/11
- **SDK used in**: Console App 
- **Framework**: .NET 7
- **Tooling**: Visual Studio 2022 64bit 17.7.3

**Comment by jansenbe** [comment] 2024-02-17 19:03
@mfxits : can you give the UpdateOverwriteVersion a try? That one uses CSOM under the covers

**Comment by mfxits** [comment] 2024-02-18 08:49
@jansenbe : that actually works.

This helps me a lot, thank you for that great advice!

I will add this info to the bug report. Because it is still a bug in UpdateAsync, I leave the issue open.

**Comment by jansenbe** [comment] 2024-02-21 07:42
@mfxits : I did check the SharePoint codebase and it appears this is by design, choice fields in document libraries are capped at 255 characters max when using the ValidateUpdateListItem API call (which we use in PnP Core SDK). For lists this limitation is not there. I'll update the docs to clarify this, but given the API works like this and there's an alternative (`SystemUpdate` or `UpdateOverwriteVersion`) I'm closing this issue now.

**Closed by jansenbe** 2024-02-21 07:42 UTC
Labels: question, area: model 📐
