### ISSUE TITLE
ISite.CreateCopyJobsAsync() throws error, but migrates files

### ISSUE THREAD

**Issue by IllBarto** [pnp/pnpcore#956] opened 2022-08-26 12:51 UTC
## Category

- [ ] Bug

## Describe the bug

Hi,

I came across this very strange situation. 

I try to use PnPCoreSDKs `ISite.CreateCopyJobsAsync()` call to move from one folder to another on the same SharePoint site a batch of 4022 files, but it always throws me a `TaskCanceledException`, although the migration of the files starts and I can see them coming in the specified location.

If I try to use the same job to move the files back to the initial folder, it fails to move some of the files, and sometimes I even end up having duplicate files - same file in both source and destination folders.

## Steps to reproduce
```
try
{
    IList<ICopyMigrationInfo> moveJobs = await context.Site.CreateCopyJobsAsync(
        fileUriGroup.ToArray(),
        destinationUri,
        new CopyMigrationOptions
        {
            AllowSchemaMismatch = true,
            AllowSmallerVersionLimitOnDestination = true,
            IgnoreVersionHistory = true,
            IsMoveMode = true,
            BypassSharedLock = true,
            NameConflictBehavior = importConfiguration.KeepBothOnSameFileName
                ? SPMigrationNameConflictBehavior.KeepBoth
                : SPMigrationNameConflictBehavior.Replace,
        }).ConfigureAwait(false);

    movingJobs.AddRange(moveJobs);
}
catch (TaskCanceledException ex)
{
    // it started the migration, but failed to retrieve the migration info objects, so we don't know when the moving is done
    // as well it could be that not all the files are moved
}
```
The call stack:
```
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at PnP.Core.Services.RetryHandlerBase.<SendAsync>d__25.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendAsync>d__2.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__70.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at PnP.Core.Services.BatchClient.<ExecuteSharePointRestInteractiveAsync>d__60.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at PnP.Core.Services.BatchClient.<ExecuteSharePointRestBatchAsync>d__52.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at PnP.Core.Services.BatchClient.<ExecuteBatch>d__37.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at PnP.Core.Model.BaseDataModel`1.<RequestAsync>d__96.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at PnP.Core.Model.BaseDataModel`1.<RawRequestAsync>d__98.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at PnP.Core.Model.SharePoint.Site.<CreateCopyJobsAsync>d__164.MoveNext()
```

## Expected behavior

The copy/move jobs are created and started, and a list of `ICopyMigrationInfo` is returned, so I can check if the migration is finished.

## Environment details (*development & target environment*)

- **SDK version**: 1.7.0
- **OS**: Windows 10
- **SDK used in**: Azure Fuctions | WinForms App
- **Framework**: .NET Core v3.1
- **Browser(s)**: Chrome | FireFox
- **Tooling**: Visual Studio 2019
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

Any help/hints is appreciated :)

**Comment by IllBarto** [comment] 2022-08-26 13:20
Just noticed this in the Console output:

```
    ------------>   IMPORT PROCESSOR: Moving a batch of 4022 files...
[2022-08-26T12:40:35.125Z] Start processing HTTP request POST https://my_sharepoint_site/_api/site/CreateCopyJobs
[2022-08-26T12:40:35.128Z] Sending HTTP request POST https://my_sharepoint_site/_api/site/CreateCopyJobs
[2022-08-26T12:42:15.142Z] Retrying request https://my_sharepoint_site/_api/site/CreateCopyJobs due to exception System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request.
[2022-08-26T12:42:15.145Z] Waiting 3 seconds before retrying
```

**Comment by jansenbe** [comment] 2022-08-26 13:27
Seems some throttling is going on here. 

PnP Core just hits the API endpoint, so if things go wrong it feels like an issue within the service. Here are the documented limitations: https://docs.microsoft.com/en-us/sharepoint/dev/apis/spod-copy-move-api#limitations.

Maybe try with a smaller batch and see if that's more reliable?

**Comment by IllBarto** [comment] 2022-08-26 16:03
I've checked the limitations and it doesn't make any sense:
> File size -> A file must be less than 2 GB.
> Number of items -> No more than 30,000 items in a job.
> Total size of job -> Job size not to exceed 100 GB.

I don't reach any of these limits, and still it fails on a batch of more than 3000 files (of random sizes, but no more than 5MB per file).
Besides this, I don't get a TimeOutException or Throttling Exception, but a TaskCanceledException, which might be a sign that the problem arises from somewhere else.

I've set the batch size of 1000 files and so far so good.

Thank you for quick reply :)

**Comment by jansenbe** [comment] 2022-08-29 17:58
@IllBarto : feels like the API is better handling smaller batches then, if you want to improve reliability for the larger batches then opening a support case via a (premier) support contract is the way forward. From the open source project we can't do that.

Since the issue is not inside PnP Core I'm going to close the issue now. Thanks for using PnP Core.

**Closed by jansenbe** 2022-08-29 17:58 UTC
Labels: question
