### ISSUE TITLE
Unable to add (create) list item to SharePoint list

### ISSUE THREAD

**Issue by DeloitteKedmiDor** [pnp/pnpcore#1384] opened 2024-02-06 16:02 UTC
## Category

- [x] Bug

## Describe the bug

Unable to add new list item to SharePoint list when list name contains "-".
Reference for the code sample used:
https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#adding-list-items

Code used:
![image](https://github.com/pnp/pnpcore/assets/152775965/b65525ba-6035-4072-b2f3-ba994933227e)

Exception snippet:
![image](https://github.com/pnp/pnpcore/assets/152775965/18ad8be5-fe4b-4923-ad54-087bd92f6238)

The list name contained "-", when I was testing it on list without "-" in the list name I was managed to create list item.

Other operations like "UpdateAsync/DeleteById" are working on existing items without any issues, it seems to me that only "Add/AddAsync/AddBatchAsync" are not working if the list name contains "-". 

## Steps to reproduce

Create new list in SharePoint site collection.
The list name should contain "-" in the name.
Try to add item using context.Web.Lists.GetByTitle("the list-name").Items.Add({the object})
Make sure the object contains "Title" property (Required) for example { "Title", "test1" }

## Expected behavior

New item should be created in the list containing the value "test1" in the "Title" column.

## Actual result

No new item created, and exception thrown.

## Environment details

Package: PnP.Core by PnP version 1.11.0
OS: windows 10
Framework: .NET Core v8.0
Tooling: Visual Studio 2022
User permissions: Full Control

**Comment by jansenbe** [comment] 2024-02-12 07:59
@DeloitteKedmiDor : thanks for reporting this, I'll have a look in the coming days (just back from a break)

**Comment by jansenbe** [comment] 2024-02-13 07:17
@DeloitteKedmiDor : I cannot reproduce this with the latest nightly, I think this was recently fixed as part of #1353. Can you retest this using the latest nightly build and see if the problem still occurs?

**Comment by jansenbe** [comment] 2024-02-16 09:16
@DeloitteKedmiDor : any update here? If not then I'll close this one

**Closed** 2024-02-16 09:17 UTC
Labels: question
