### ISSUE TITLE
UpdateOverwriteVersionAsync creates a draft version of the page 

### ISSUE THREAD

**Issue by wpo365** [pnp/pnpcore#754] opened 2022-02-09 22:04 UTC
## Category

- [x] Bug

## Describe the bug

I have followed [this example](https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#updating-the-list-item-author-editor-created-and-modified-system-properties) to update the Editor field and it creates a draft version (of a published modern SharePoint page) instead of leaving it published as it was before the code was executed.

## Steps to reproduce

To reproduce it simply copy / paste [this code](https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#updating-the-list-item-author-editor-created-and-modified-system-properties) and apply it to a SharePoint modern page that previously was published. It will create a new draft version instead of leaving the page published and overwriting the existing published version.

## Expected behavior

The page's editor (and author, created and modified) fields can be updated without creating a new draft version.

## Environment details (*development & target environment*)

- **SDK version**: 1.4.75 Nightly
- **OS**: Windows 10
- **SDK used in**: Console App
- **Framework**: net5
- **Browser(s)**: Edge 98
- **Tooling**: Visual Studio 2022

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by patrikhellgren** [comment] 2022-02-09 23:14
@wpo365 You cannot overwrite a published file, the SharePoint API doesn't allow it as you also can see in the UI. What you can do is first unpublish it (which will demote the version to the last draft version), call UpdateOverwriteVersionAsync and then publish it again. This will end up with the same major version as it was before but being updated.

**Comment by wpo365** [comment] 2022-02-10 06:29
@patrikhellgren But that means that it is not possible to update the Editor value. Because I can update it but as soon as I re-publish the page with another (technical) user it will set the Editor to that specific user. Or have I overlooked another way of achieving this?

**Comment by jansenbe** [comment] 2022-02-10 07:20
@wpo365 : that's correct, if you work with major/minor versions in a library than you can't update a published version without resetting the Editor/Changed values.

**Comment by wpo365** [comment] 2022-02-10 07:39
@jansenbe Understood and glad this is now confirmed, even though - in my opinion - this makes UpdateOverwriteVersionAsync pretty useless. In my scenario we are migrating an intranet from classic to modern and around 4000 pages will now appear to be published by a technical account.

**Comment by jansenbe** [comment] 2022-02-10 07:46
@wpo365 : Maybe migrate the pages to the target pages library without major/minor versioning setup, ensure author/editor/modified/created are set correctly. Once all pages are done enable major/minor versioning again. At that point the present files are marked as published with the author/editor/modified/created you've set. You'll only be able to migrate the last version (which is what commonly is done) and the version number will be 1.0 for all of them but it might be a workaround.

**Comment by jansenbe** [comment] 2022-02-10 08:58
Closing as this is "as designed" by SharePoint, nothing PnP Core SDK can change here.

**Closed by jansenbe** 2022-02-10 08:58 UTC

**Comment by heinrich-ulbricht** [comment] 2022-10-05 11:27
I just verified that this works as workaround: 

1. switch versioning setting for Pages Library from **Create major and minor (draft) versions** to **Create major versions**
2. create page with editor/changed values set - this creates a new major version
3. switch versioning setting back to **Create major and minor (draft) versions**

This looks good. Now what about pages currently having a minor version? It seems like they just keep it while switching minor versions off and on. @jansenbe Is that a safe assumption to make? Because then the guidance for bulk-creating published pages with specific Editor would be:

1. Schedule a maintenance window where no user is active
2. Switch the Pages Library to **Create major versions**
3. Create pages
4. Switch the Pages Library back to **Create major and minor (draft) versions** 
5. End the maintenance window

All good?

**Comment by wpo365** [comment] 2022-11-22 22:02
@jansenbe @heinrich-ulbricht Yes, I can also confirm that the approach of disabling minor versions did the trick! Thanks and sorry for the late response.
