### ISSUE TITLE
Set a Folder Column default value using "SetDefaultColumnValuesAsync" will cause all the current folders' column defaul values to be cleared.

### ISSUE THREAD

**Issue by mvcsharepointdev** [pnp/pnpcore#1119] opened 2023-02-27 13:01 UTC
## Category

- [x] Bug

## Describe the bug

when using SetDefaultColumnValuesAsync to set a column default value for a folder, all the current columns default values for all the folders will be cleared

## Steps to reproduce

> Here is my method to set a default column value using PnP Core SDK:-

```
private async Task SetDefaultAsync(string folderpath, string fieldname, FieldTaxonomyValue term, PnP.Core.Model.SharePoint.IList mylist)
        {
         

            List<DefaultColumnValueOptions> defaultColumnValues = new()
{
    new DefaultColumnValueOptions
    {
        FolderRelativePath = folderpath,
        FieldInternalName = fieldname,
        DefaultValue =$"-1;#{term.Label}|{term.TermId}"
    }
            };

          

            await mylist.SetDefaultColumnValuesAsync(defaultColumnValues);

        }
```

## Expected behavior

The expected behavior should be that the current folder will get the needed default values, without reseting any current folders' column default values.

In CSOM i use to do so using this code:-

```
List listtooperate = context.Web.GetList(webrelativeurl + "/" + template["TemplateListUrl"].ToString());
MetadataDefaults bb = new MetadataDefaults(context, listtooperate);

        if (listItem["CorpType"] != null)
             {

               var corpTypetaxValue = listItem["CorpType"] as TaxonomyFieldValue;
               if (corpTypetaxValue != null)
                   {
                                 
                      bb.SetFieldDefault(context.Web.GetFolderByServerRelativeUrl(webrelativeurl + "/" + template["TemplateListUrl"].ToString() + "/" + mainfoldername.ToString()), "CorpType", "1033;#" + corpTypetaxValue.Label + "|" + corpTypetaxValue.TermGuid);
                      bb.Update();

                     }
       }

```
so can i do the same using PnP core SDK ?

Thank

## Environment details (*development & target environment*)

I am using the PnP Core SDK version 1.8 and SharePoint online

**Comment by jansenbe** [comment] 2023-02-27 15:59
This is by design @mvcsharepointdev , when you provide new defaults the previous ones are overwritten. If you want to update existing default values then you need to first get the existing default values via `var loadedDefaults = await myList.GetDefaultColumnValuesAsync();` and then update the returned collection of defaults before saving them back via `SetDefaultColumnValuesAsync`.

Closing per design.

**Closed as completed by jansenbe** 2023-02-27 15:59 UTC

**Comment by mvcsharepointdev** [comment] 2023-02-27 16:56
@jansenbe  but using CSOM is it possible to update a single folder .. is there any workaround for this?

**Comment by jansenbe** [comment] 2023-02-27 17:20
There's no CSOM approach...it's custom code in PnP Framework...which initially also has to fetch the existing configuration before saving. Performance wise there's no issue as the default values are stored in one XML file inside the Forms folder...the code you're using is wrapper on top of that.

**Comment by mvcsharepointdev** [comment] 2023-02-27 17:42
@jansenbe  what do you mean by there is not CSOM appraoch, i posted some CSOM code which allow us to update the defualt column values without clear/rest anything

**Comment by jansenbe** [comment] 2023-02-28 06:37
@mvcsharepointdev : interesting, wasn't aware of the CSOM approach and therefore I copied the model we used previously in PnP Framework. In PnP Core SDK we try to avoid CSOM calls if possible and since this class is not exposed to REST it would mean we have to use CSOM. The workaround I suggested results in the same behavior and there's no performance concern, even for a huge amount of folders.
