### ISSUE TITLE
team.Archive(setSPOSiteReadOnlyForMembers) not working

### ISSUE THREAD

**Issue by Nevinia210** [pnp/pnpcore#1185] opened 2023-05-22 08:32 UTC
## Category

- [ ] Bug

## Describe the bug

after team.Archive(true); is called, associated sp site is not set readonly for members,
our current solution is :
1. creation of CSOM context from deprecated SharePointPnPCoreOnline
2. get tenant context
3. load site properties from selected associated site
4. set LockState to "ReadOnly"  ( siteProperties.LockState = "ReadOnly";)

Is there possibility to Archive team and set associated sp site to readonly as well in PnPCore?

## Expected behavior

associated sp site is set to readonly for members

## Environment details (*development & target environment*)

version of sp: SPO
PnP.Core: 1.9.0 (used in different places in solution)
SharePointPnPCoreOnline: 3.28.2012
Windows: 10

**Comment by jansenbe** [comment] 2023-05-22 09:03
@Nevinia210 : yes this is possible in PnP Core SDK. See https://pnp.github.io/pnpcore/using-the-sdk/admin-sharepoint-sites.html#getting-and-setting-site-collection-properties to learn more. The ´LockState´ property is defined like this: https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core.Admin/Model/SharePoint/Core/Public/ISiteCollectionProperties.cs#L231-L237

**Comment by Nevinia210** [comment] 2023-05-22 11:21
@jansenbe,
thanks for reply, i didnt notice this article in the first place, when i used that approach in my code, for setting site to readonly it works without any issues, but then setting it back to not-readonly  it throws an error for access denied, is there some additional permissions needed when comparing setting site to readonly and back?

**Comment by jansenbe** [comment] 2023-05-22 12:43
@Nevinia210 : is the account you're using part of the Tenant SharePoint Administrators?

**Comment by Nevinia210** [comment] 2023-05-22 12:50
@jansenbe 
im using app registration with api permissions:
![image](https://github.com/pnp/pnpcore/assets/42325625/95c9bfbb-056e-4681-908e-4a9edd645799)

**Comment by jansenbe** [comment] 2023-05-22 13:06
@Nevinia210 : I think you need to be either a Tenant SharePoint Administrator or  Global tenant administrator to make the unlock work. Under the covers this approach uses CSOM, so wondering why this works with CSOM in an old PnP package?

Note that the fact that the Teams Archive call is not working is by design since you're using application permissions (https://learn.microsoft.com/en-us/graph/api/team-archive?view=graph-rest-1.0&tabs=http#request-body).

**Comment by jansenbe** [comment] 2023-05-24 18:39
@Nevinia210 : closing this one as it's by design

**Closed by jansenbe** 2023-05-24 18:39 UTC
Labels: question, area: model 📐
