### ISSUE TITLE
Error: Task Canceled when loading items by Caml query

### ISSUE THREAD

**Issue by bajce** [pnp/pnpcore#619] opened 2021-11-11 12:51 UTC
I'm TaskCanceled exception on list.LoadItemsByCamlQuery(...).

In order to read "all" SharePoint data faster, I'm using different Task and split the work among them. Each of those tasks have own PnPContext (which can be reused for same Web if no other Task is using it). Error occurs on different ListItems.

StackTrace:
`   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.Services.BatchClient.<ExecuteSharePointRestBatchAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.Services.BatchClient.<ExecuteBatch>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.Model.BaseDataModel`1.<RequestAsync>d__93.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.Model.SharePoint.List.<LoadItemsByCamlQueryAsync>d__164.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PnP.Core.Model.SharePoint.List.LoadItemsByCamlQuery(CamlQueryOptions queryOptions, Expression`1[] selectors)`

**Comment by jansenbe** [comment] 2021-11-11 13:22
@bajce : just to understand...you are using different `PnPContext` instances for different sites, but you use them in parallel to read data from those different sites? Did you validate that reading these lists using a single `PnPContext` does work?

If you can reproduce this is a console application that would be great, the stacktrace does not really help understanding where things go wrong

**Comment by bajce** [comment] 2021-11-11 14:29
@jansenbe Yes I created `PnPContext` pool (size 10) by URL and I use them in parallel. Idea is that every time I need the context for specific URL I can take it from the pool instead of cloning it every time or creating new one in order to improve performance in huge SharePoint structures. When I set pool size to 1 I can't reproduce the error, it seams like everything works as expected. 

I can try do reproduce it in console application.

**Comment by jansenbe** [comment] 2021-11-11 15:41
@bajce : also ensure you are using the latest version when testing

**Comment by jansenbe** [comment] 2021-11-15 19:30
@bajce : any update here?

**Comment by bajce** [comment] 2021-11-17 11:12
@jansenbe I was using the latest nightly version. Unfortunately not, I won't have that much time soon to reproduce it in console application as it can take longer. I totally understand if you want to close the issue, once I have the console application which reproduces it I can reopen it (if possible) or create new one.

**Comment by jansenbe** [comment] 2021-11-17 12:08
Let's close for now @bajce , but feel free to either re-open or create a new one.

**Comment by gopaldahal** [comment] 2023-01-12 08:37
Don't know the root cause for this. But I am getting the same behaviour on my end too. However the behaviour is unusual and appears randomly while reading list items. To be added.. the reading is done parallelly on multiple threads.

     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Services.BatchClient.<ExecuteSharePointRestInteractiveAsync>d__60.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at PnP.Core.Services.BatchClient.<ExecuteSharePointRestBatchAsync>d__52.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at PnP.Core.Services.BatchClient.<ExecuteBatch>d__37.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Model.BaseDataModel`1.<BaseRetrieveAsync>d__65.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Services.PnPContextFactory.<InitializeContextAsync>d__55.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Services.PnPContextFactory.<CreateAsync>d__46.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Services.PnPContextFactory.<CreateAsync>d__41.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Services.PnPContextFactory.Create(Uri url, PnPContextOptions options)
   at XYZ.Common.PnPCoreHandler.PnPCoreAuthentication.<CreatePnPContext>d__4.MoveNext() in C:\Projects\Deployer\TzDE2 .net2\XYZ.Common.PnPCoreHandler\PnPCoreAuthentication.cs:line 149
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at XYZ.Common.PnPCoreHandler.PnPCoreAuthentication.<GetPnPCoreClientContext>d__3.MoveNext() in C:\Projects\Deployer\TzDE2 .net2\XYZ.Common.PnPCoreHandler\PnPCoreAuthentication.cs:line 125

**Comment by jansenbe** [comment] 2023-01-21 08:31
@gopaldahal : the error happens during the `PnPContext` initialization...might help to take a look at what data is being loaded as part of the context initialization. The default set of data is described here https://pnp.github.io/pnpcore/using-the-sdk/basics-context.html#loading-additional-iweb-and-isite-properties-when-creating-a-pnpcontext, but maybe you're loading additional data?

If you try the same web again it then works?

**Comment by jansenbe** [comment] 2023-02-10 15:05
Closing per no feedback

**Closed by jansenbe** 2023-02-10 15:05 UTC
Labels: question
