### ISSUE TITLE
[BUG] Get-PnPSiteTemplate Error While Generating Template

### ISSUE THREAD

**Issue by teofilosalgado** [pnp/pnpcore#389] opened 2021-04-01 20:29 UTC
### Reporting an Issue or Missing Feature
The `Get-PnPSiteTemplate` is failing to create a template for a given site. I've tested the site beforehand with `Test-PnPSite` and no errors were found.

### Expected behavior 
The `Get-PnPSiteTemplate` command should create an XML template representing the given site.

### Actual behavior 
The command is returning the following error:
```
Get-PnPSiteTemplate : Oops...seems we end up here anyway...check PnP.Framework code to understand what was here
At C:\Users\joaosalgado\workspace\SharePointBackupTools\src\Export-SharePointSiteTemplate.ps1:45 char:9
+         Get-PnPSiteTemplate `
+         ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPSiteTemplate], Exception
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate
```
After running `Get-PnPException` I got the following stack:
```
Message          : Oops...seems we end up here anyway...check PnP.Framework code to understand what was here
Stacktrace       :    at PnP.Core.Model.SharePoint.PageWebPart.FromHtml(IElement element)
                      at PnP.Core.Model.SharePoint.Page.LoadFromHtml(String html, String pageHeaderHtml)
                      at PnP.Core.Model.SharePoint.Page.<LoadPageAsync>d__121.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at PnP.Core.Model.SharePoint.Page.<LoadPagesAsync>d__93.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at PnP.Core.Model.SharePoint.Web.<GetPagesAsync>d__282.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at PnP.Core.Model.SharePoint.Web.GetPages(String pageName)
                      at Microsoft.SharePoint.Client.PageExtensions.LoadClientSidePage(Web web, String pageName)
                      at PnP.Framework.Provisioning.ObjectHandlers.Utilities.ClientSidePageContentsHelper.ExtractClientSidePage(Web 
                   web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo, PnPMonitoredScope 
                   scope, PageToExport page)
                      at PnP.Framework.Provisioning.ObjectHandlers.ObjectClientSidePageContents.ExtractObjects(Web web, 
                   ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo)
                      at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, 
                   ProvisioningTemplateCreationInformation creationInfo)
                      at PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate.ExtractTemplate(XMLPnPSchemaVersion schema, 
                   String path, String packageName, ExtractConfiguration configuration)
                      at PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
```
### Steps to reproduce behavior
Just run the following command in a Powershell session.
```
        Get-PnPSiteTemplate `
            -Out $TemplatePath `
            -IncludeAllTermGroups `
            -IncludeSiteCollectionTermGroup `
            -IncludeSiteGroups `
            -PersistBrandingFiles `
            -PersistPublishingFiles `
            -IncludeNativePublishingFiles `
            -IncludeAllPages `
            -Handlers All `
            -Schema LATEST `
            -Force;
```
### What is the version of the Cmdlet module you are running?
1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by rhdorneles** [comment] 2021-04-09 18:45
Hi @teofilosalgado .

If you collect a fiddler probably you will see some 429 http status code. That means that your requests are being throttled (too many requests per second) by SharePoint. 

PnP has a mechanism that keeps trying about 10 times... if SharePoint throttle 9-10 times PnP command will stop and throw an error.

So, check the Fiddler when reproducing the issue for 429 http code, probably you will see 9-10 requests with this status.

I believe that your site is large, making the PnP does all these requests. 

@erwinvanhunen Maybe can explain better the PnP mechanism to avoid SharePoint Throttling.

Hope that information helps you.

**Comment by teofilosalgado** [comment] 2021-04-09 19:21
@rhdorneles yeah, it definitely helped. Coincidently, I asked Microsoft Support for help a few minutes ago and they collected a fiddler from my computer. After analyzing it we've got the same status code you pointed out. My site is indeed very large (around 200GB currently). After some googling, I've stumbled upon [this](https://github.com/pnp/powershell/discussions/62) discussion so it seems to be possible to deal with large sites I just couldn't figure how. I even tried to create a simple C# project using pnp/framework's `GetProvisioningTemplate`  but didn't manage to circumvent the aforementioned limitations 😢. 

As a side note, I ported my Powershell code to use the now-retired ([source ](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps)) SharePointPnPPowerShellOnline library and template provisioning works like a charm.

**Comment by jansenbe** [comment] 2021-04-15 18:28
@teofilosalgado : There was an issue with working with pages in large pages libraries, the errors where slightly different but it might help to try again with a more recent nightly.

The error you showed can show-up in 2 cases I'm currently aware of:
- when you're using pages with additional controls in the page header: viva topic pages are such pages...I actually today fixed a bug for that
- we used to have an issue with 3rd party web parts which where hosted in an iframe (due to domain isolation)...as that was a temporary thing I've not ported the code fix for that from the old library to PnP Core SDK...

Would be good if you could verify the above 2 conditions.

**Comment by teofilosalgado** [comment] 2021-04-15 21:07
Hi @jansenbe! So, I checked all of my pages and none of them contain 3rd party web parts or additional controls in their headers. Actually, most of my pages are just plain text with a few tables.
Currently, as a workaround, I decided to create a template for every single page of my website using `Export-PnPClientSidePage` and later on iterating through each .XML file publishing the templates with `Export-PnPClientSidePage`.

**Comment by jansenbe** [comment] 2021-04-16 08:32
@teofilosalgado : So when exporting page by page it works...while exporting all pages at once results in the mentioned error?

**Comment by teofilosalgado** [comment] 2021-04-16 12:21
Yeah, exactly. Here is a snippet of my template extraction code:
```
Connect-PnPOnline -Url $Url -UseWebLogin;
$PageList = Get-PnPListItem -List "SitePages";
$ResultPath = Resolve-Path ".\Result";

foreach ($PageItem in $PageList) {
    $Name = $PageItem.FieldValues["FileLeafRef"];
    $Guid = $PageItem.FieldValues["GUID"];
    $TemplateFolderPath = Join-Path -Path $ResultPath -ChildPath $Guid;
    $TemplateFilePath = Join-Path -Path $TemplateFolderPath -ChildPath "Template.xml";

    Export-PnPClientSidePage `
         -Identity $Name `
         -Out $TemplateFilePath `
         -PersistBrandingFiles `
         -ErrorAction Stop `
         -Force;
}
```
And here is the script that applies the templates:
```
Connect-PnPOnline -Url $DestinationUrl -UseWebLogin;
$Templates = Import-Csv -Path ".\Result\Log.csv"; # Log.csv is a list of every template and it's location in the disk

foreach($Template in $Templates){
    $TemplatePath = $Template.Path;
    Apply-PnPProvisioningTemplate -Path $TemplatePath -ClearNavigation;
}
```

**Comment by rhdorneles** [comment] 2021-04-16 12:43
@jansenbe .
In the fiddler that @teofilosalgado collected during the error is clear that SharePoint online is throttling PnP requests. (HTTPS status 429). Probably is the quantity of requests per second, maybe because he has a huge site with many pages. I don’t think his site has an issue.

Is there a way to control in the PnP the quantity of requests per second? Maybe if it does less requests in a short amount of time that issue will not happen.

**Comment by jansenbe** [comment] 2021-04-16 13:53
@rhdorneles : PnP follows the throttling guidance and will back off when being throttled...that however can still result in failures if the throttle is persistent. We've no option to limit the amount of requests being made. As there's a workaround and the root cause is throttling there's no changes needed from the PnP side, so I'll close the issue.

**Closed by jansenbe** 2021-04-16 13:53 UTC
Labels: area: pages API 📄, question
