### ISSUE TITLE
Page LikeByInformation - Page.GetLikedByInformationAsync() is not retreiving any information about page likes

### ISSUE THREAD

**Issue by NishkalankBezawada** [pnp/pnpcore#1395] opened 2024-02-16 15:20 UTC
## Category

- [x] Bug

## Describe the bug

I am trying to get the Page LikedByInformation as below, 

`var pageLikeInformation = clientSidePage.GetLikedByInformationAsync().GetAwaiter().GetResult();` 

But i get no results when using this. 

I also used GetCommentsAsync() to get the comment collection which works fine. 
`var commentsCollection = clientSidePage.GetCommentsAsync().GetAwaiter().GetResult();`

Below code is working and getting likedByInformation as well.
`
              var pageNew = await pnpContext.Web.NewPageAsync();

                // Save the page
                await pageNew.SaveAsync("Pageb.aspx");

                // Publish the page, required before it can be liked
                await pageNew.PublishAsync();

                // Like the page
                await pageNew.LikeAsync();

                var pageLikeInformation = await pageNew.GetLikedByInformationAsync();
                bool pageLikedByCurrentUser = pageLikeInformation.IsLikedByUser;
                foreach (var likedByUser in pageLikeInformation.LikedBy.AsRequested())
                {
                    // do something with the information about the user who liked this page
                }
`

Below code is not working,

`
                var mypages =  await pnpContext.Web.GetPagesAsync("TestingLikeInfo.aspx");
                var pageABC = mypages.First();

                await pageABC.PublishAsync();
                ILikedByInformation likeInfo2 = await pageABC.GetLikedByInformationAsync();
                bool pageLikedByCurrentUser2 = likeInfo2.IsLikedByUser;
`

## Expected behavior
`await pageABC.GetLikedByInformationAsync();`  should get LikedByInformation

## Library
PnP.Core - 1.11.69-nightly

Thanks,
Nishkalank

**Comment by jansenbe** [comment] 2024-02-19 18:33
@NishkalankBezawada : not sure what the issue is here, I've tested https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core.Test/SharePoint/PagesTests.cs#L2728-L2775 and this works fine. A page can be liked, the like can be retrieved and the page can be unliked.

If I try below then `GetLikedByInformation` returns on instance saying there are no likes on the page.

```csharp
// Save the page
await newPage.SaveAsync(pageName);

// Publish the page, required before it can be liked
newPage.Publish();

// Like the page
//newPage.Like();

// Get a list of users who liked this page
var pageLikeInformation = newPage.GetLikedByInformation();
```

**Comment by NishkalankBezawada** [comment] 2024-02-19 19:44
Thanks @jansenbe for your prompt reply. 

I am trying to fetch a page LikedByInformation as below (which is having more than 3 likes), 
```
var mypages =  await pnpContext.Web.GetPagesAsync("TestingLikeInfo.aspx");
var pageABC = mypages.First();
ILikedByInformation likeInfo = await pageABC.GetLikedByInformationAsync();
```

This should return me the LikedInformation of that particular page,  but `GetLikedByInformationAsync` returns no likes on that particular page. 

`GetLikedByInformationAsync`  works only when i create it, save, publish it, and then like it as below

`
              var pageNew = await pnpContext.Web.NewPageAsync();

                // Save the page
                await pageNew.SaveAsync("Pageb.aspx");

                // Publish the page, required before it can be liked
                await pageNew.PublishAsync();

                // Like the page
                await pageNew.LikeAsync();

                var pageLikeInformation = await pageNew.GetLikedByInformationAsync();
                bool pageLikedByCurrentUser = pageLikeInformation.IsLikedByUser;
                foreach (var likedByUser in pageLikeInformation.LikedBy.AsRequested())
                {
                    // do something with the information about the user who liked this page
                }
`

**Comment by jansenbe** [comment] 2024-02-20 07:23
@NishkalankBezawada : thanks, I can now reproduce the issue you're seeing. Let me work on a fix

**Comment by NishkalankBezawada** [comment] 2024-02-20 07:25
> @NishkalankBezawada : thanks, I can now reproduce the issue you're seeing. Let me work on a fix

Thanks once again Jensen @jansenbe 

Regards,
Nish

**Comment by jansenbe** [comment] 2024-02-20 09:10
@NishkalankBezawada : I fixed this, please test again with the next nightly build. Will close this issue now, feel free to re-open in case the problem stays.

**Closed by jansenbe** 2024-02-20 09:10 UTC
Labels: question, area: model 📐
