### ISSUE TITLE
Setting the localized name of a TermSet is not possible

### ISSUE THREAD

**Issue by JuergenRB** [pnp/pnpcore#1188] opened 2023-05-24 22:38 UTC
## Category

- [x] Bug

## Describe the bug

The documentation describes how to set the LocalizedName of a TermSet. 
However, the example does not work because the **TermSetLocalizedNameCollection** class is **internal**. 

![image](https://github.com/pnp/pnpcore/assets/22403655/6a8f6400-08bc-4cad-9ea4-4c74d4b08b7e)

## Steps to reproduce

Proceed as described in the [documentation](https://pnp.github.io/pnpcore/using-the-sdk/taxonomy-intro.html#working-with-term-sets)

```csharp
// Add a new localized label for the term set
(termSet.LocalizedNames as TermSetLocalizedNameCollection).Add(new TermSetLocalizedName() { LanguageTag = "nl-NL", Name = "Dutch name" });
// Send the updates to the server
await termSet.UpdateAsync();
```

## Expected behavior

The example from the documentation works or there is another possibility to set the LocalizedNames of the TermSets.

**Comment by jansenbe** [comment] 2023-05-25 14:59
@JuergenRB : thanks for using PnP Core SDK and reporting this @JuergenRB , our test projects can see "internals", this indeed needs to be fixed.

**Comment by jansenbe** [comment] 2023-05-25 16:11
@JuergenRB : I've just pushed a fix, when you test with our nightly build tomorrow you can use following approach:

```csharp
// Update termset 
termSet.Description = "updated description";
termSet.AddLocalizedName("Dutch name", "nl-NL");
await termSet.UpdateAsync();
```

**Comment by jansenbe** [comment] 2023-05-25 16:12
@JuergenRB : I'm closing this one already, feel free to re-open or create a new issue in case the problem is still not resolved for you.

**Closed by jansenbe** 2023-05-25 16:12 UTC
Labels: bug, area: model 📐
