### ISSUE TITLE
PnPContext GetSiteCollectionManager().GetSiteCollectionsWithDetailsAsync(null, true) throwing exception

### ISSUE THREAD

**Issue by valpvt** [pnp/pnpcore#1143] opened 2023-03-24 14:29 UTC
## Category

- [x] Bug

## Describe the bug

> While using PnpContext GetSiteCollectionManager().GetSiteCollectionsWithDetailsAsync(null, true) the method is throwing an exception because a site collection is not retrieved (returned 404)

## Steps to reproduce

> Use GetSiteCollectionManager().GetSiteCollectionsWithDetailsAsync(null, true) after private channels were deleted

## Expected behavior

> Log missing site collection without throwing an exception for the whole method

## Environment details (*development & target environment*)

> 

- **SDK version**: 1.8.140-nightly
- **OS**: W10
- **SDK used in**:Console App
- **Framework**: .Net 6.0
- **Tooling**: VS Code

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment] 2023-03-24 14:55
@valpvt : can you share the stacktrace?

**Comment by valpvt** [comment] 2023-03-24 15:23
@jansenbe Yes, here is the stacktrace 
`      End processing HTTP request after 56.7644ms - 404
System.Net.Http.HttpClient.SharePointRestClient.LogicalHandler: Information: End processing HTTP request after 56.7644ms - 404
Exception thrown: 'PnP.Core.SharePointRestServiceException' in System.Private.CoreLib.dll
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.13\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.13\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.13\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
   at PnP.Core.Services.BatchClient.ExecuteSharePointRestBatchAsync(Batch batch)
   at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch)
   at PnP.Core.Services.PnPContext.ExecuteAsync(Batch batch, Boolean throwOnError)
   at PnP.Core.Admin.Model.SharePoint.SiteCollectionEnumerator.GetWithDetailsViaTenantAdminHiddenListAsync(PnPContext context, VanityUrlOptions vanityUrlOptions, Boolean includeSharedAndPrivateTeamChannelSites, Int32 pageSize)
   at PnP.Core.Admin.Model.SharePoint.SiteCollectionManager.GetSiteCollectionsWithDetailsAsync(VanityUrlOptions vanityUrlOptions, Boolean includeSharedAndPrivateTeamChannelSites)`

**Comment by jansenbe** [comment] 2023-03-24 15:52
@valpvt : this helps, so the REST call that queries the sites list goes is generating an error. You have an option to create a fiddler trace and send it to me? (bjansen@microsoft.com)

**Comment by valpvt** [comment] 2023-03-24 16:28
@jansenbe  Unfortunately I am behind corporate proxy at the moment and can't get fiddler traces 😞

**Comment by jansenbe** [comment] 2023-03-24 17:03
@valpvt : can you catch the exception and get the underlying error returned by SharePoint? See https://pnp.github.io/pnpcore/using-the-sdk/basics-errorhandling.html#catching-a-pnp-core-sdk-exception-and-getting-the-exception-details for sample code on how to that

**Comment by valpvt** [comment] 2023-03-29 08:06
Hi @jansenbe ,
Sorry for the delay, below is the underlying error I caught :
`PnP.Core.SharePointRestServiceException: SharePoint Rest service exception
   at PnP.Core.Services.BatchClient.ExecuteSharePointRestBatchAsync(Batch batch)
   at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch)
   at PnP.Core.Services.PnPContext.ExecuteAsync(Batch batch, Boolean throwOnError)
   at PnP.Core.Admin.Model.SharePoint.SiteCollectionEnumerator.GetWithDetailsViaTenantAdminHiddenListAsync(PnPContext context, VanityUrlOptions vanityUrlOptions, Boolean includeSharedAndPrivateTeamChannelSites, Int32 pageSize)
   at PnP.Core.Admin.Model.SharePoint.SiteCollectionManager.GetSiteCollectionsWithDetailsAsync(VanityUrlOptions vanityUrlOptions, Boolean includeSharedAndPrivateTeamChannelSites)
Exception thrown: 'System.NullReferenceException' in SPInventory.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.`

**Comment by jansenbe** [comment] 2023-03-29 08:46
@valpvt : so the error stays, even after the private channel was removed a while ago? You still have other private channels in that tenant?

**Comment by valpvt** [comment] 2023-03-29 09:19
> @valpvt : so the error stays, even after the private channel was removed a while ago? You still have other private channels in that tenant?

Yes the error stays when the private channel was removed for a while, the only way I found to go further was to permanently delete with PowerShell command. We have many private channels in our tenant and I cannot do this for all deleted channels ☹

**Comment by jansenbe** [comment] 2023-03-29 09:35
@valpvt : how did you delete it with PS?

**Comment by jansenbe** [comment] 2023-03-29 09:59
@valpvt : I just tried to repro this but could not. I've deleted a private channel (via the Teams UI) and it was not included anymore in the resulting list. Seems that in your case the hidden list in tenant admin is out of sync with reality and therefore the site is still returned. This then blows up in the code that loads the site to get additional information:

![image](https://user-images.githubusercontent.com/7451219/228498516-087c3f4d-d307-4a69-b2b8-b54df122638a.png)

You can verify/debug this via our SourceLink support: https://pnp.github.io/pnpcore/using-the-sdk/basics-debug.html

**Comment by jansenbe** [comment] 2023-04-19 06:56
@valpvt : did you manage to debug this? Is this still an issue for you?

**Comment by jansenbe** [comment] 2023-04-21 07:44
@valpvt : I'm closing this issue now. We can't reproduce + there's been no recent feedback. If you see this different then please re-open or create a new issue with additional context.

**Closed as completed by jansenbe** 2023-04-21 07:44 UTC
Labels: bug, area:admin 📜
