### ISSUE TITLE
Unable to enumerate permissions unless the user is a site collection admin

### ISSUE THREAD

**Issue by jaygoodison** [pnp/pnpcore#1345] opened 2024-01-10 12:13 UTC
## Category

- [X] Bug

## Describe the bug
**Setup:** SPFX command set using an AD Auth Web App to call SharePoint via PnP Core

Consider the following two lines of code which will load an IFile object and role assignments info:

IFile sourceFile = await pnpContext.Web.GetFileByServerRelativeUrlAsync($"{path}//{fileName}");
await sourceFile.ListItemAllFields.LoadAsync(p => p.HasUniqueRoleAssignments, p => p.RoleAssignments.QueryProperties(d => d.RoleDefinitions));

This works fine if the user is a site collection admin, however it fails if the current user only has the 'Full Control' permission level to the current web.

## Exception Details
- PnP.Core.SharePointRestServiceException: 'SharePoint Rest service exception'
- System.UnauthorizedAccessException
- Attempted to perform an unauthorized operation.

## Expected behavior
We're struggling to find any documentation to confirm what permisison levels are required to enumerate permissions, however the 'Full Control' permission level contains the 'Manage Permissions' and 'Enumerate Permissions' rights so... this should work for a user with only 'Full Control' permissions? 

## Environment details (*development & target environment*)

- **SDK version**: 1.8.0
- **OS**: [e.g. Windows 11
- **SDK used in**: ASP.Net Web app
- **Framework**:.NET Corev6 
- **Browser(s)**:N/A
- **Tooling**: VS Code | Visual Studio 2022

**Comment by jansenbe** [comment] 2024-01-10 17:37
@jaygoodison : I assume this is by design if that's what you are seeing. My guess that SharePoint needs to execute code that needs to get data from the root site and since you've broken permission inheritance this failing. These concepts have been around for a very long time and are quite stable, so don't expect this be a bug, and for sure not a bug in PnP Core SDK. Therefore I'm closing this issue.

**Closed by jansenbe** 2024-01-10 17:37 UTC
Labels: question
